### ISSUE TITLE
hyper async await example tokio::spawn failed

### ISSUE THREAD

**Issue by dvic** [tokio-rs/tokio#1098]
## Version
```
examples v0.1.0 (/usr/rust/external/tokio/async-await)
├── bytes v0.4.12
│   ├── byteorder v1.3.1
│   ├── either v1.5.2
│   └── iovec v0.1.2
│       └── libc v0.2.55
├── futures v0.1.27
├── hyper v0.12.29
│   ├── bytes v0.4.12 (*)
│   ├── futures v0.1.27 (*)
│   ├── futures-cpupool v0.1.8
│   │   ├── futures v0.1.27 (*)
│   │   └── num_cpus v1.10.0
│   │       └── libc v0.2.55 (*)
│   ├── h2 v0.1.20
│   │   ├── byteorder v1.3.1 (*)
│   │   ├── bytes v0.4.12 (*)
│   │   ├── fnv v1.0.6
│   │   ├── futures v0.1.27 (*)
│   │   ├── http v0.1.17
│   │   │   ├── bytes v0.4.12 (*)
│   │   │   ├── fnv v1.0.6 (*)
│   │   │   └── itoa v0.4.4
│   │   ├── indexmap v1.0.2
│   │   ├── log v0.4.6
│   │   │   └── cfg-if v0.1.9
│   │   ├── slab v0.4.2
│   │   ├── string v0.1.3
│   │   └── tokio-io v0.1.12
│   │       ├── bytes v0.4.12 (*)
│   │       ├── futures v0.1.27 (*)
│   │       └── log v0.4.6 (*)
│   ├── http v0.1.17 (*)
│   ├── http-body v0.1.0
│   │   ├── bytes v0.4.12 (*)
│   │   ├── futures v0.1.27 (*)
│   │   ├── http v0.1.17 (*)
│   │   └── tokio-buf v0.1.1
│   │       ├── bytes v0.4.12 (*)
│   │       ├── either v1.5.2 (*)
│   │       └── futures v0.1.27 (*)
│   ├── httparse v1.3.3
│   ├── iovec v0.1.2 (*)
│   ├── itoa v0.4.4 (*)
│   ├── log v0.4.6 (*)
│   ├── net2 v0.2.33
│   │   ├── cfg-if v0.1.9 (*)
│   │   └── libc v0.2.55 (*)
│   ├── time v0.1.42
│   │   └── libc v0.2.55 (*)
│   │   [dev-dependencies]
│   │   └── winapi v0.3.7
│   ├── tokio v0.1.20
│   │   ├── bytes v0.4.12 (*)
│   │   ├── futures v0.1.27 (*)
│   │   ├── mio v0.6.17
│   │   │   ├── iovec v0.1.2 (*)
│   │   │   ├── libc v0.2.55 (*)
│   │   │   ├── log v0.4.6 (*)
│   │   │   ├── net2 v0.2.33 (*)
│   │   │   └── slab v0.4.2 (*)
│   │   ├── num_cpus v1.10.0 (*)
│   │   ├── tokio-current-thread v0.1.6
│   │   │   ├── futures v0.1.27 (*)
│   │   │   └── tokio-executor v0.1.7
│   │   │       ├── crossbeam-utils v0.6.5
│   │   │       │   ├── cfg-if v0.1.9 (*)
│   │   │       │   └── lazy_static v1.3.0
│   │   │       └── futures v0.1.27 (*)
│   │   ├── tokio-executor v0.1.7 (*)
│   │   ├── tokio-io v0.1.12 (*)
│   │   ├── tokio-reactor v0.1.9
│   │   │   ├── crossbeam-utils v0.6.5 (*)
│   │   │   ├── futures v0.1.27 (*)
│   │   │   ├── lazy_static v1.3.0 (*)
│   │   │   ├── log v0.4.6 (*)
│   │   │   ├── mio v0.6.17 (*)
│   │   │   ├── num_cpus v1.10.0 (*)
│   │   │   ├── parking_lot v0.7.1
│   │   │   │   ├── lock_api v0.1.5
│   │   │   │   │   ├── owning_ref v0.4.0
│   │   │   │   │   │   └── stable_deref_trait v1.1.1
│   │   │   │   │   └── scopeguard v0.3.3
│   │   │   │   └── parking_lot_core v0.4.0
│   │   │   │       ├── libc v0.2.55 (*)
│   │   │   │       ├── rand v0.6.5
│   │   │   │       │   ├── libc v0.2.55 (*)
│   │   │   │       │   ├── rand_chacha v0.1.1
│   │   │   │       │   │   └── rand_core v0.3.1
│   │   │   │       │   │       └── rand_core v0.4.0
│   │   │   │       │   │   [build-dependencies]
│   │   │   │       │   │   └── autocfg v0.1.2
│   │   │   │       │   ├── rand_core v0.4.0 (*)
│   │   │   │       │   ├── rand_hc v0.1.0
│   │   │   │       │   │   └── rand_core v0.3.1 (*)
│   │   │   │       │   ├── rand_isaac v0.1.1
│   │   │   │       │   │   └── rand_core v0.3.1 (*)
│   │   │   │       │   ├── rand_jitter v0.1.4
│   │   │   │       │   │   ├── libc v0.2.55 (*)
│   │   │   │       │   │   └── rand_core v0.4.0 (*)
│   │   │   │       │   ├── rand_os v0.1.3
│   │   │   │       │   │   ├── libc v0.2.55 (*)
│   │   │   │       │   │   └── rand_core v0.4.0 (*)
│   │   │   │       │   ├── rand_pcg v0.1.2
│   │   │   │       │   │   └── rand_core v0.4.0 (*)
│   │   │   │       │   │   [build-dependencies]
│   │   │   │       │   │   └── autocfg v0.1.2 (*)
│   │   │   │       │   └── rand_xorshift v0.1.1
│   │   │   │       │       └── rand_core v0.3.1 (*)
│   │   │   │       │   [build-dependencies]
│   │   │   │       │   └── autocfg v0.1.2 (*)
│   │   │   │       └── smallvec v0.6.9
│   │   │   │       [build-dependencies]
│   │   │   │       └── rustc_version v0.2.3
│   │   │   │           └── semver v0.9.0
│   │   │   │               └── semver-parser v0.7.0
│   │   │   ├── slab v0.4.2 (*)
│   │   │   ├── tokio-executor v0.1.7 (*)
│   │   │   ├── tokio-io v0.1.12 (*)
│   │   │   └── tokio-sync v0.1.5
│   │   │       ├── fnv v1.0.6 (*)
│   │   │       └── futures v0.1.27 (*)
│   │   │   [dev-dependencies]
│   │   │   └── num_cpus v1.10.0 (*)
│   │   ├── tokio-threadpool v0.1.14
│   │   │   ├── crossbeam-deque v0.7.1
│   │   │   │   ├── crossbeam-epoch v0.7.1
│   │   │   │   │   ├── arrayvec v0.4.10
│   │   │   │   │   │   └── nodrop v0.1.13
│   │   │   │   │   ├── cfg-if v0.1.9 (*)
│   │   │   │   │   ├── crossbeam-utils v0.6.5 (*)
│   │   │   │   │   ├── lazy_static v1.3.0 (*)
│   │   │   │   │   ├── memoffset v0.2.1
│   │   │   │   │   └── scopeguard v0.3.3 (*)
│   │   │   │   └── crossbeam-utils v0.6.5 (*)
│   │   │   ├── crossbeam-queue v0.1.2
│   │   │   │   └── crossbeam-utils v0.6.5 (*)
│   │   │   ├── crossbeam-utils v0.6.5 (*)
│   │   │   ├── futures v0.1.27 (*)
│   │   │   ├── log v0.4.6 (*)
│   │   │   ├── num_cpus v1.10.0 (*)
│   │   │   ├── rand v0.6.5 (*)
│   │   │   ├── slab v0.4.2 (*)
│   │   │   └── tokio-executor v0.1.7 (*)
│   │   ├── tokio-timer v0.2.11
│   │   │   ├── crossbeam-utils v0.6.5 (*)
│   │   │   ├── futures v0.1.27 (*)
│   │   │   ├── slab v0.4.2 (*)
│   │   │   └── tokio-executor v0.1.7 (*)
│   │   └── tokio-trace-core v0.1.0
│   │       └── lazy_static v1.3.0 (*)
│   │   [dev-dependencies]
│   │   └── num_cpus v1.10.0 (*)
│   ├── tokio-buf v0.1.1 (*)
│   ├── tokio-executor v0.1.7 (*)
│   ├── tokio-io v0.1.12 (*)
│   ├── tokio-reactor v0.1.9 (*)
│   ├── tokio-tcp v0.1.3
│   │   ├── bytes v0.4.12 (*)
│   │   ├── futures v0.1.27 (*)
│   │   ├── iovec v0.1.2 (*)
│   │   ├── mio v0.6.17 (*)
│   │   ├── tokio-io v0.1.12 (*)
│   │   └── tokio-reactor v0.1.9 (*)
│   ├── tokio-threadpool v0.1.14 (*)
│   ├── tokio-timer v0.2.11 (*)
│   └── want v0.0.6
│       ├── futures v0.1.27 (*)
│       ├── log v0.4.6 (*)
│       └── try-lock v0.2.2
│   [build-dependencies]
│   └── rustc_version v0.2.3 (*)
└── tokio v0.2.0 (/usr/rust/external/tokio/tokio)
    ├── bytes v0.4.12 (*)
    ├── futures v0.1.27 (*)
    ├── mio v0.6.17 (*)
    ├── num_cpus v1.10.0 (*)
    ├── tokio-codec v0.2.0 (/usr/rust/external/tokio/tokio-codec)
    │   ├── bytes v0.4.12 (*)
    │   ├── futures v0.1.27 (*)
    │   └── tokio-io v0.2.0 (/usr/rust/external/tokio/tokio-io)
    │       ├── bytes v0.4.12 (*)
    │       ├── futures v0.1.27 (*)
    │       └── log v0.4.6 (*)
    ├── tokio-current-thread v0.2.0 (/usr/rust/external/tokio/tokio-current-thread)
    │   ├── futures v0.1.27 (*)
    │   └── tokio-executor v0.2.0 (/usr/rust/external/tokio/tokio-executor)
    │       ├── crossbeam-utils v0.6.5 (*)
    │       └── futures v0.1.27 (*)
    ├── tokio-executor v0.2.0 (/usr/rust/external/tokio/tokio-executor) (*)
    ├── tokio-fs v0.2.0 (/usr/rust/external/tokio/tokio-fs)
    │   ├── futures v0.1.27 (*)
    │   ├── tokio-io v0.2.0 (/usr/rust/external/tokio/tokio-io) (*)
    │   └── tokio-threadpool v0.2.0 (/usr/rust/external/tokio/tokio-threadpool)
    │       ├── crossbeam-deque v0.7.1 (*)
    │       ├── crossbeam-queue v0.1.2 (*)
    │       ├── crossbeam-utils v0.6.5 (*)
    │       ├── futures v0.1.27 (*)
    │       ├── log v0.4.6 (*)
    │       ├── num_cpus v1.10.0 (*)
    │       ├── rand v0.6.5 (*)
    │       ├── slab v0.4.2 (*)
    │       └── tokio-executor v0.2.0 (/usr/rust/external/tokio/tokio-executor) (*)
    ├── tokio-futures v0.2.0 (/usr/rust/external/tokio/tokio-futures)
    │   ├── futures v0.1.27 (*)
    │   └── tokio-io v0.2.0 (/usr/rust/external/tokio/tokio-io) (*)
    ├── tokio-io v0.2.0 (/usr/rust/external/tokio/tokio-io) (*)
    ├── tokio-macros v0.1.0 (/usr/rust/external/tokio/tokio-macros)
    │   ├── proc-macro2 v0.4.30
    │   │   └── unicode-xid v0.1.0
    │   ├── quote v0.6.12
    │   │   └── proc-macro2 v0.4.30 (*)
    │   └── syn v0.15.34
    │       ├── proc-macro2 v0.4.30 (*)
    │       ├── quote v0.6.12 (*)
    │       └── unicode-xid v0.1.0 (*)
    ├── tokio-reactor v0.2.0 (/usr/rust/external/tokio/tokio-reactor)
    │   ├── crossbeam-utils v0.6.5 (*)
    │   ├── futures v0.1.27 (*)
    │   ├── lazy_static v1.3.0 (*)
    │   ├── log v0.4.6 (*)
    │   ├── mio v0.6.17 (*)
    │   ├── num_cpus v1.10.0 (*)
    │   ├── parking_lot v0.7.1 (*)
    │   ├── slab v0.4.2 (*)
    │   ├── tokio-executor v0.2.0 (/usr/rust/external/tokio/tokio-executor) (*)
    │   ├── tokio-io v0.2.0 (/usr/rust/external/tokio/tokio-io) (*)
    │   └── tokio-sync v0.2.0 (/usr/rust/external/tokio/tokio-sync)
    │       ├── fnv v1.0.6 (*)
    │       └── futures v0.1.27 (*)
    │   [dev-dependencies]
    │   └── num_cpus v1.10.0 (*)
    ├── tokio-sync v0.2.0 (/usr/rust/external/tokio/tokio-sync) (*)
    ├── tokio-tcp v0.2.0 (/usr/rust/external/tokio/tokio-tcp)
    │   ├── bytes v0.4.12 (*)
    │   ├── futures v0.1.27 (*)
    │   ├── iovec v0.1.2 (*)
    │   ├── mio v0.6.17 (*)
    │   ├── tokio-io v0.2.0 (/usr/rust/external/tokio/tokio-io) (*)
    │   └── tokio-reactor v0.2.0 (/usr/rust/external/tokio/tokio-reactor) (*)
    ├── tokio-threadpool v0.2.0 (/usr/rust/external/tokio/tokio-threadpool) (*)
    ├── tokio-timer v0.3.0 (/usr/rust/external/tokio/tokio-timer)
    │   ├── crossbeam-utils v0.6.5 (*)
    │   ├── futures v0.1.27 (*)
    │   ├── slab v0.4.2 (*)
    │   └── tokio-executor v0.2.0 (/usr/rust/external/tokio/tokio-executor) (*)
    ├── tokio-trace-core v0.1.0 (*)
    ├── tokio-udp v0.2.0 (/usr/rust/external/tokio/tokio-udp)
    │   ├── bytes v0.4.12 (*)
    │   ├── futures v0.1.27 (*)
    │   ├── log v0.4.6 (*)
    │   ├── mio v0.6.17 (*)
    │   ├── tokio-codec v0.2.0 (/usr/rust/external/tokio/tokio-codec) (*)
    │   ├── tokio-io v0.2.0 (/usr/rust/external/tokio/tokio-io) (*)
    │   └── tokio-reactor v0.2.0 (/usr/rust/external/tokio/tokio-reactor) (*)
    └── tokio-uds v0.2.5
        ├── bytes v0.4.12 (*)
        ├── futures v0.1.27 (*)
        ├── iovec v0.1.2 (*)
        ├── libc v0.2.55 (*)
        ├── log v0.4.6 (*)
        ├── mio v0.6.17 (*)
        ├── mio-uds v0.6.7
        │   ├── iovec v0.1.2 (*)
        │   ├── libc v0.2.55 (*)
        │   └── mio v0.6.17 (*)
        ├── tokio-codec v0.1.1
        │   ├── bytes v0.4.12 (*)
        │   ├── futures v0.1.27 (*)
        │   └── tokio-io v0.1.12 (*)
        ├── tokio-io v0.1.12 (*)
        └── tokio-reactor v0.1.9 (*)
    [dev-dependencies]
    └── num_cpus v1.10.0 (*)
```

## Platform

`Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`

## Description
When I run `cargo run --bin=hyper`, I get the error below.

Steps to reproduce (from my branch with the async-await-preview feature fix #1097)
1. `git clone https://github.com/dvic/tokio/`
2. `git checkout async-await-preview-feature-fix`
3. `cd async-await`
4. `cargo +nightly run --bin=hyper`

Is this because `hyper` is pulling in `tokio 0.1` and missing the thread-local set executor?

```
RUST_BACKTRACE=1 cargo +nightly run --bin=hyper
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `../target/debug/hyper`
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Inner(Error(User(Execute), "tokio::spawn failed (is a tokio runtime running this future?)")))', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libcore/result.rs:800
  10: hyper::main::{{closure}}
             at src/hyper.rs:16
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/future.rs:39
  12: std::future::set_task_context
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/future.rs:74
  13: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/future.rs:39
  14: <tokio_futures::compat::infallible_into_01::Map<T> as core::future::future::Future>::poll
             at /usr/rust/external/tokio/tokio-futures/src/compat/mod.rs:34
  15: <tokio_futures::compat::backward::Compat<T> as futures::future::Future>::poll
             at /usr/rust/external/tokio/tokio-futures/src/compat/backward.rs:52
  16: futures::future::chain::Chain<A,B,C>::poll
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/chain.rs:26
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/then.rs:32
  18: hashbrown::raw::bitmask::BitMask::invert
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/mod.rs:113
  19: tokio_threadpool::worker::entry::WorkerEntry::set_next_sleeper
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:329
  20: tokio_threadpool::worker::entry::WorkerEntry::set_next_sleeper
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:399
  21: tokio_threadpool::shutdown::ShutdownTrigger::new
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:83
  22: tokio_threadpool::worker::entry::WorkerEntry::set_next_sleeper
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:399
  23: tokio_threadpool::worker::entry::WorkerEntry::set_next_sleeper
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:291
  24: tokio_threadpool::worker::entry::WorkerEntry::set_next_sleeper
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:329
  25: tokio_threadpool::task::Task::run::{{closure}}
             at /usr/rust/external/tokio/tokio-threadpool/src/task/mod.rs:143
  26: core::ops::function::FnOnce::call_once
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libcore/ops/function.rs:231
  27: <tokio_threadpool::pool::backup_stack::State as core::cmp::PartialEq>::ne
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panic.rs:309
  28: <tokio_threadpool::config::Config as core::clone::Clone>::clone
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panicking.rs:293
  29: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  30: <tokio_threadpool::config::Config as core::clone::Clone>::clone
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panicking.rs:272
  31: <tokio_threadpool::pool::backup_stack::State as core::cmp::PartialEq>::ne
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panic.rs:388
  32: tokio_threadpool::task::Task::run
             at /usr/rust/external/tokio/tokio-threadpool/src/task/mod.rs:128
  33: tokio_threadpool::worker::Worker::run_task2
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:565
  34: tokio_threadpool::worker::Worker::run_task
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:457
  35: tokio_threadpool::worker::Worker::try_run_owned_task
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:388
  36: tokio_threadpool::worker::Worker::try_run_task
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:295
  37: tokio_threadpool::worker::Worker::do_run
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:239
  38: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /usr/rust/external/tokio/tokio/src/runtime/threadpool/builder.rs:358
  39: std::sys::unix::mutex::Mutex::destroy
             at /Users/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-trace-core-0.1.0/src/dispatcher.rs:54
  40: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /usr/rust/external/tokio/tokio/src/runtime/threadpool/builder.rs:357
  41: core::ptr::real_drop_in_place
             at /usr/rust/external/tokio/tokio-timer/src/timer/handle.rs:99
  42: core::fmt::Arguments::new_v1
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:299
  43: core::fmt::Arguments::new_v1
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:245
  44: core::ptr::real_drop_in_place
             at /usr/rust/external/tokio/tokio-timer/src/timer/handle.rs:82
  45: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /usr/rust/external/tokio/tokio/src/runtime/threadpool/builder.rs:356
  46: <core::time::Duration as core::cmp::PartialOrd>::le
             at /usr/rust/external/tokio/tokio-timer/src/clock/clock.rs:135
  47: core::fmt::Arguments::new_v1
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:299
  48: core::fmt::Arguments::new_v1
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:245
  49: <core::time::Duration as core::cmp::PartialOrd>::le
             at /usr/rust/external/tokio/tokio-timer/src/clock/clock.rs:115
  50: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /usr/rust/external/tokio/tokio/src/runtime/threadpool/builder.rs:355
  51: <log::Level as core::cmp::PartialOrd<log::LevelFilter>>::le
             at /usr/rust/external/tokio/tokio-reactor/src/lib.rs:221
  52: core::fmt::Arguments::new_v1
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:299
  53: core::fmt::Arguments::new_v1
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:245
  54: <log::Level as core::cmp::PartialOrd<log::LevelFilter>>::le
             at /usr/rust/external/tokio/tokio-reactor/src/lib.rs:201
  55: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /usr/rust/external/tokio/tokio/src/runtime/threadpool/builder.rs:354
  56: tokio_threadpool::callback::Callback::call
             at /usr/rust/external/tokio/tokio-threadpool/src/callback.rs:20
  57: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:125
  58: <usize as core::default::Default>::default
             at /usr/rust/external/tokio/tokio-executor/src/global.rs:202
  59: <tokio_threadpool::worker::state::Lifecycle as core::cmp::PartialEq>::eq
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:299
  60: <tokio_threadpool::worker::state::Lifecycle as core::cmp::PartialEq>::eq
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:245
  61: <usize as core::default::Default>::default
             at /usr/rust/external/tokio/tokio-executor/src/global.rs:171
  62: tokio_threadpool::worker::Worker::do_run::{{closure}}
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:123
  63: <tokio_threadpool::worker::state::Lifecycle as core::cmp::PartialEq>::eq
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:299
  64: <tokio_threadpool::worker::state::Lifecycle as core::cmp::PartialEq>::eq
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/local.rs:245
  65: tokio_threadpool::worker::Worker::do_run
             at /usr/rust/external/tokio/tokio-threadpool/src/worker/mod.rs:114
  66: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at /usr/rust/external/tokio/tokio-threadpool/src/pool/mod.rs:342
  67: core::clone::impls::<impl core::clone::Clone for usize>::clone
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/sys_common/backtrace.rs:136
  68: tokio_threadpool::thread_pool::ThreadPool::new2
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/mod.rs:469
  69: <tokio_threadpool::pool::backup_stack::State as core::cmp::PartialEq>::ne
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panic.rs:309
  70: <tokio_threadpool::config::Config as core::clone::Clone>::clone
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panicking.rs:293
  71: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  72: <tokio_threadpool::config::Config as core::clone::Clone>::clone
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panicking.rs:272
  73: <tokio_threadpool::pool::backup_stack::State as core::cmp::PartialEq>::ne
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/panic.rs:388
  74: tokio_threadpool::thread_pool::ThreadPool::new2
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/thread/mod.rs:468
  75: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libcore/ops/function.rs:231
  76: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/liballoc/boxed.rs:704
  77: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/liballoc/boxed.rs:704
             at src/libstd/sys_common/thread.rs:13
             at src/libstd/sys/unix/thread.rs:79
  78: _pthread_body
  79: _pthread_start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libcore/result.rs:800
  10: tokio::runtime::threadpool::Runtime::block_on
             at /usr/rust/external/tokio/tokio/src/runtime/threadpool/mod.rs:262
  11: tokio::runtime::threadpool::async_await::<impl tokio::runtime::threadpool::Runtime>::block_on_async
             at /usr/rust/external/tokio/tokio/src/runtime/threadpool/async_await.rs:13
  12: hyper::main
             at src/hyper.rs:10
  13: std::rt::lang_start::{{closure}}
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/rt.rs:64
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  15: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  16: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: std::rt::lang_start
             at /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libstd/rt.rs:64
  18: hyper::main
```

**Comment by carllerche** [comment]
Thanks for the report.

The async-await examples are removed on nightly (for now). This issue was caused by crate version problems, which should no longer be a problem once the examples come back.
