### ISSUE TITLE
Possible thread leak on macOS 10.10 in Security.Framework?

### ISSUE THREAD

**Issue by mqudsi** [tokio-rs/tokio#1232]
## Version

Direct dependency on `futures = 0.1`,  `tokio-core = 0.1`, and a separate dependency on `hyper = 0.12` giving the following dependency tree:

```
│   │   └── tokio-io v0.1.12
│   │   └── tokio-buf v0.1.1
│   ├── tokio v0.1.21
│   │   ├── tokio-codec v0.1.1
│   │   │   └── tokio-io v0.1.12 (*)
│   │   ├── tokio-current-thread v0.1.6
│   │   │   └── tokio-executor v0.1.7
│   │   ├── tokio-executor v0.1.7 (*)
│   │   ├── tokio-fs v0.1.6
│   │   │   ├── tokio-io v0.1.12 (*)
│   │   │   └── tokio-threadpool v0.1.14
│   │   │
└── tokio-executor v0.1.7 (*)
│   │   │   └── tokio-io v0.1.12 (*)
│   │   ├── tokio-io v0.1.12 (*)
│   │   ├── tokio-reactor v0.1.9
│   │   │   ├── tokio-executor v0.1.7 (*)
│   │   │   ├── tokio-io v0.1.12 (*)
│   │   │   └── tokio-sync v0.1.5
│   │   ├── tokio-sync v0.1.5 (*)
│   │   ├── tokio-tcp v0.1.3
│   │   │   ├── tokio-io v0.1.12 (*)
│   │   │   └── tokio-reactor v0.1.9 (*)
│   │   ├── tokio-threadpool v0.1.14 (*)
│   │   ├── tokio-timer v0.2.11
│   │   │   └── tokio-executor v0.1.7 (*)
│   │   ├── tokio-trace-core v0.2.0
│   │   ├── tokio-udp v0.1.3
│   │   │   ├── tokio-codec v0.1.1 (*)
│   │   │   ├── tokio-io v0.1.12 (*)
│   │   │   └── tokio-reactor v0.1.9 (*)
│   │   └── tokio-uds v0.2.5
│   │
├── tokio-codec v0.1.1 (*)
│   │
├── tokio-io v0.1.12 (*)
│   │
└── tokio-reactor v0.1.9 (*)
│   ├── tokio-buf v0.1.1 (*)
│   ├── tokio-executor v0.1.7 (*)
│   ├── tokio-io v0.1.12 (*)
│   ├── tokio-reactor v0.1.9 (*)
│   ├── tokio-tcp v0.1.3 (*)
│   ├── tokio-threadpool v0.1.14 (*)
│   ├── tokio-timer v0.2.11 (*)
│   └── tokio-io v0.1.12 (*)
├── tokio-core v0.1.17
│   ├── tokio v0.1.21 (*)
│   ├── tokio-executor v0.1.7 (*)
│   ├── tokio-io v0.1.12 (*)
│   ├── tokio-reactor v0.1.9 (*)
│   └── tokio-timer v0.2.11 (*)
```

## Platform

macOS Yosemite 10.10 amd64

```
Darwin MacBook.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
```

## Description

**NB: It's hard for me to pin this down but I was using an older version of tokio, hyper, and other dependencies and had some non-idiomatic code so I spent a few days upgrading everything to the latest version to make sure the bug report was as relevant as possible.**

Running on macOS Yosemite 10.10 (for backwards compatibility reasons), I have observed that an application starting up a tokio executor via `hyper-rs`, after a few days the server process ends up with a thousand+ threads, all stuck in macOS's `Security.Framework` at the same spot.

Here's a screenshot showing the thread count:

![image](https://user-images.githubusercontent.com/606923/60400766-3ae6e980-9b3e-11e9-90fa-e72317c878bb.png)

And in `gdb`, here's what `info threads` looks like:

```
  Id   Target Id Frame
* 1    Thread 0x1603 of process 67263  0x00007fff9b824136 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  2    Thread 0x1703 of process 67263  0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  3    Thread 0x1803 of process 67263  0x00007fff9b824166 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  4    Thread 0x1903 of process 67263  0x00007fff9b824166 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  5    Thread 0x1a03 of process 67263  0x00007fff9b824136 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  6    Thread 0x1b03 of process 67263  0x00007fff9b824166 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  7    Thread 0x1c03 of process 67263  0x00007fff9b825232 in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  8    Thread 0x1d03 of process 67263  0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  9    Thread 0x1e03 of process 67263  0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  10   Thread 0x1f03 of process 67263  0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  11   Thread 0x2003 of process 67263  0x00007fff9b824136 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  12   Thread 0x2103 of process 67263  0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  13   Thread 0x2203 of process 67263  0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  14   Thread 0x2303 of process 67263  0x00007fff9b824136 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
⋮
  1361 Thread 0x56603 of process 67263 0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
  1362 Thread 0x56703 of process 67263 0x00007fff9b82521a in construction vtable for Security::CssmClient::ObjectImpl-in-Security::CssmClient::TPImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security

```

For any given thread, the backtrace is as follows:

```
(gdb) bt
#0  0x00007fff9b824136 in construction vtable for Security::CssmClient::CSPImpl-in-Security::CssmClient::CSPDLImpl () from /System/Library/Frameworks/Security.framework/Versions/A/Security
#1  0x00007fff92494560 in _pthread_cond_wait () from /usr/lib/system/libsystem_pthread.dylib
#2  0x000000010ccc2586 in futures::task_impl::std::ThreadNotify::park ()
#3  0x000000010cabbddc in std::thread::local::LocalKey<T>::with ()
#4  0x000000010ca05843 in tokio_executor::enter::Enter::block_on ()
#5  0x000000010ca69251 in tokio::runtime::threadpool::run ()
#6  0x000000010caf428e in messagebridge::main ()
#7  0x000000010ca71626 in std::rt::lang_start::{{closure}} ()
#8  0x000000010cce2f58 in std::io::read_to_end_with_reservation () at src/libstd/io/mod.rs:377
#9  std::panicking::try::do_call () at src/libstd/io/mod.rs:356
#10 0x000000010cce2f40 in core::ptr::<impl *mut T>::offset () at /rustc/7840a0b753a065a41999f1fb6028f67d33e3fdd5/src/libcore/ptr/mod.rs:1705
#11 core::ptr::<impl *mut T>::add () at /rustc/7840a0b753a065a41999f1fb6028f67d33e3fdd5/src/libcore/ptr/mod.rs:1943
#12 <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::get_unchecked_mut () at /rustc/7840a0b753a065a41999f1fb6028f67d33e3fdd5/src/libcore/slice/mod.rs:2738
#13 <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut () at /rustc/7840a0b753a065a41999f1fb6028f67d33e3fdd5/src/libcore/slice/mod.rs:2761
#14 <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index_mut () at /rustc/7840a0b753a065a41999f1fb6028f67d33e3fdd5/src/libcore/slice/mod.rs:2832
#15 core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut () at /rustc/7840a0b753a065a41999f1fb6028f67d33e3fdd5/src/libcore/slice/mod.rs:2562
#16 <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut () at /rustc/7840a0b753a065a41999f1fb6028f67d33e3fdd5/src/liballoc/vec.rs:1768
#17 std::io::read_to_end_with_reservation () at src/libstd/io/mod.rs:376
#18 std::panicking::update_panic_count () at src/libstd/io/mod.rs:356
#19 0x0000000000000000 in ?? ()
```

The application is still running OK and servicing requests just fine at this point (although it will run out of resources if left this way indefinitely).

I no longer directly spawn any tasks/futures (although I was careful with how I was doing so previously) in an attempt to make sure I don't have any problems in the code itself. 

As I was using the old version of hyper that required an external core, my code basically has two executors, one I start in the main and another that hyper starts internally. I know I can use my own reactor to run hyper as well, but I didn't see the need since it's just one extra thread at startup (in case this information helps). The one in the hotpath is the executor spawned by hyper, the other one is only used by sporadic hyper client instances where handling a request necessitates a call to a remote resource.

I can't tell if the threads are basically parked (or deadlocked) in `pthread_cond_wait` and that just shows up as a call to `Security.Framework` or if there is actually something else happening. It seems almost like the call to `pthread_cond_wait` is triggering a static initializer in `Security.Framework`, but I am surprised at [the lack of results](https://www.google.com/search?safe=off&biw=2046&bih=943&ei=VAoZXayYJ-LL5gKB9Yy4Aw&q=%22_pthread_cond_wait%22+%22Security%3A%3ACssmClient%3A%3ACSPImpl-in-Security%22&oq=%22_pthread_cond_wait%22+%22Security%3A%3ACssmClient%3A%3ACSPImpl-in-Security%22&gs_l=psy-ab.3...8168.8168..8369...0.0..0.73.73.1......0....1..gws-wiz.bP8gyJ7lq6s) for the relevant search.

This was compiled with rust 1.37.0 nightly from 2019-05-31. I wasn't sure if I should ask about this here, but it seemed like the most appropriate avenue to bring it up at least until I can understand what's actually happening. (I also admit I'm not sure whether or not the @Amanieu's parking_lot code is powering the thread parking here or not.)

I have to look through the code again to double-check, but could mingling futures from the two separate cores cause this?

**Comment by carllerche** [comment]
Thanks for the issue report. Do you have a minimal repro demonstrating the issue?

**Comment by mqudsi** [comment]
I do not. Do you have a tokio stress test I could run?

**Comment by carllerche** [comment]
We have a number of stress tests in our test suite. You could try running the test suite and see.

**Comment by carllerche** [comment]
I ask for a minimal repro to rule out a bug in your code.

**Comment by mqudsi** [comment]
> I ask for a minimal repro to rule out a bug in your code.

I understand, and because I don't at the moment have that I was wondering if there was some kind of test you already had that I could pound and not have it quit afterwards, giving me a chance to see if it reproduces on this OS even with the stock code.

tbh, if I had a minimal repro I'd have submitted a PR ;)

I did try to pin down what part of the code spawns new threads, but it does not seem to be as simple as "one future of a certain type spawned == one os thread started and hung" because I was not able to directly observe a one-to-one correlation between a single future being created on my end to an increase in the process' LWP count.
