### ISSUE TITLE
Is the tokio threadpool fork safe?

### ISSUE THREAD

**Issue by jefshe** [tokio-rs/tokio#1541]
Hi,
I'm using tokio in an application server (hyper). The server is multithreaded and I have 1 background thread which forks the current process and runs some rust code.

I've noticed that sometimes the server runs into deadlocks. My current theory is that this is due to my forked process holding onto locks required by tokio's threadpool but I really have no idea about the details of the implementation of tokio's threadpool

I observe on my unix machine that there are multiple processes launched by the threadpool which are stuck on an epoll_wait syscall:

```
#0  0x00007ff3762e5007 in epoll_wait () from /usr/lib/libc.so.6
#1  0x00005602bff5d707 in mio::sys::unix::epoll::Selector::select (self=0x5602c09e80e0, evts=0x7ff372b560b8, awakener=..., timeout=...) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/sys/unix/epoll.rs:72
#2  0x00005602bff5018b in mio::poll::Poll::poll2 (self=0x5602c09e80e0, events=0x7ff372b560b8, timeout=..., interruptible=false) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:1178
#3  0x00005602bff4fe75 in mio::poll::Poll::poll1 (self=0x5602c09e80e0, events=0x7ff372b560b8, timeout=..., interruptible=false) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:1139
#4  0x00005602bff4f707 in mio::poll::Poll::poll (self=0x5602c09e80e0, events=0x7ff372b560b8, timeout=...) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:1010
#5  0x00005602bff205b6 in tokio_net::driver::reactor::Reactor::poll (self=0x7ff372b560b8, max_wait=...) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-net-0.2.0-alpha.4/src/driver/reactor.rs:241
#6  0x00005602bff1cdd9 in tokio_net::driver::reactor::Reactor::turn (self=0x7ff372b560b8, max_wait=...) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-net-0.2.0-alpha.4/src/driver/reactor.rs:225
#7  0x00005602bff1d699 in <tokio_net::driver::reactor::Reactor as tokio_executor::park::Park>::park (self=0x7ff372b560b8) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-net-0.2.0-alpha.4/src/driver/reactor.rs:333
#8  0x00005602bfe55491 in <tokio_timer::timer::Timer<T,N> as tokio_executor::park::Park>::park (self=0x7ff372b56090) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.3.0-alpha.4/src/timer/mod.rs:372
#9  0x00005602bfe42c74 in tokio_executor::current_thread::Entered<P>::block_on (self=0x7ff372b56038, future=...) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.4/src/current_thread/mod.rs:481
#10 0x00005602bfe43475 in tokio_executor::current_thread::CurrentThread<P>::block_on (self=0x7ff372b56068, future=...) at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.4/src/current_thread/mod.rs:314
#11 0x00005602bfe3dfdb in tokio::runtime::threadpool::background::spawn::{{closure}} () at /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.0-alpha.4/src/runtime/threadpool/background.rs:34
#12 0x00005602bfe3a625 in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/sys_common/backtrace.rs:77
#13 0x00005602bfe3fbd1 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/thread/mod.rs:470
#14 0x00005602bfe420f4 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=()) at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:315
#15 0x00005602bfe3abae in std::panicking::try::do_call (data=0x7ff372b56510 "\240\201\236\300\002V\000") at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:296
#16 0x00005602c012419a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:80
#17 0x00005602bfe3aa10 in std::panicking::try (f=...) at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
#18 0x00005602bfe436c6 in std::panic::catch_unwind (f=...) at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
#19 0x00005602bfe3f9c2 in std::thread::Builder::spawn_unchecked::{{closure}} () at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/thread/mod.rs:469
#20 0x00005602bfe3adc4 in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
#21 0x00005602c0111a6f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
#22 0x00005602c01234e0 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
#23 std::sys_common::thread::start_thread () at src/libstd/sys_common/thread.rs:13
#24 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:79
#25 0x00007ff3763d0a92 in start_thread () from /usr/lib/libpthread.so.0
#26 0x00007ff3762e4cd3 in clone () from /usr/lib/libc.so.6
```

Is it never safe to fork a rust process running one of these thread pools?

**Comment by alecmocatta** [comment]
Forking when there's more than one thread running is inadvisable in general as it easily deadlocks: thread B takes out a lock (e.g. in the malloc implementation), thread A forks, thread B releases the lock, new process C never has that lock unlocked.

**Comment by carllerche** [comment]
Exactly ^^ Threads + fork is bad news... you _can_ fork **if** you immediately exec and do not allocate memory or perform any other operation that may have been corrupted by the fork.
