### ISSUE TITLE
Deadlock when dropping runtime

### ISSUE THREAD

**Issue by bmwill** [tokio-rs/tokio#1948]
## Version

tokio v0.2.4

## Description

There is a deadlock when dropping a Runtime that is built to work in a single-threaded scenario. Specifically the following program won't ever exit. (This program can be run with the corresponding helloworld-server from the tonic repo).

```rust
use tokio::runtime::{Builder, Runtime};

pub mod hello_world {
    tonic::include_proto!("helloworld");
}

use hello_world::{client::GreeterClient, HelloRequest};

type Result<T> = ::std::result::Result<T, Box<dyn std::error::Error>>;

// Drop Deadlocks on this struct if fields are ordered with `client` first and `rt` second,
// but drop is NOT deadlocked when ordered with `rt` first and `client` second.
struct SyncClient {
    client: GreeterClient<tonic::transport::Channel>,
    rt: Runtime,
}

impl SyncClient {
    pub fn new(address: &'static str) -> Result<Self> {
        let mut rt = Builder::new()
            .basic_scheduler()
            .enable_all()
            .build()
            .unwrap();
        let client = rt.block_on(GreeterClient::connect(address))?;

        Ok(Self { client, rt })
    }

    pub fn say_hello(&mut self) -> Result<()> {
        let request = tonic::Request::new(HelloRequest {
            name: "Tonic".into(),
        });
        let response = self.rt.block_on(self.client.say_hello(request))?;
        println!("RESPONSE={:?}", response);

        Ok(())
    }
}

fn main() -> Result<()> {
    let mut client = SyncClient::new("http://[::1]:50051")?;

    client.say_hello()?;

    Ok(())
}
```

<details>
    <summary> Stack Trace </summary>

```
Program received signal SIGINT, Interrupt.
0x00007ffff77c14ed in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) where
#0  0x00007ffff77c14ed in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007ffff77bcdcb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007ffff77bcc98 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000555555c4cf0a in std::sys::unix::mutex::Mutex::lock (self=0x55555610fc90)
    at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/sys/unix/mutex.rs:55
#4  0x0000555555c87501 in std::sys_common::mutex::Mutex::raw_lock (self=0x55555610fc90)
    at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/sys_common/mutex.rs:36
#5  0x0000555555c4dd95 in std::sync::mutex::Mutex<T>::lock (self=0x55555610fd18)
    at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/sync/mutex.rs:220
#6  0x0000555555c2b822 in tokio::task::queue::MpscQueues<S>::remote (self=0x55555610fcf0)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/queue.rs:115
#7  0x0000555555c65e49 in <tokio::runtime::basic_scheduler::SchedulerPriv as tokio::task::Schedule>::schedule (self=0x55555610fcf0, task=...)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/basic_scheduler.rs:273
#8  0x0000555555802a99 in tokio::task::harness::Harness<T,S>::wake_by_ref (self=0x7fffffffcd10)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:315
#9  0x00005555558030be in tokio::task::harness::Harness<T,S>::wake_by_val (self=...)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:299
#10 0x000055555581ca44 in tokio::task::waker::wake_by_val (ptr=0x555556119a40)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/waker.rs:84
#11 0x0000555555cc94d2 in core::task::wake::Waker::wake (self=...) at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/task/wake.rs:252
#12 0x0000555555cc860e in futures_core::task::__internal::atomic_waker::AtomicWaker::wake (self=0x555556110210)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.1/src/task/__internal/atomic_waker.rs:355
#13 0x000055555588b39c in futures_channel::mpsc::SenderInner<T>::close_channel (self=0x555556110e98)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.1/src/mpsc/mod.rs:567
#14 0x000055555588c796 in <futures_channel::mpsc::SenderInner<T> as core::ops::drop::Drop>::drop (self=0x555556110e98)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.1/src/mpsc/mod.rs:795
#15 0x0000555555852d15 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#16 0x00005555558515d6 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#17 0x000055555584aba1 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#18 0x000055555585202a in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#19 0x0000555555851671 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#20 0x000055555584c207 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#21 0x0000555555850392 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#22 0x000055555584e6c9 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#23 0x000055555584fde9 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#24 0x0000555555853e09 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#25 0x000055555584b491 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#26 0x000055555584e571 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#27 0x0000555555763408 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#28 0x000055555575edc1 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#29 0x000055555576331e in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#30 0x0000555555760f65 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#31 0x00005555557616b1 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#32 0x00005555557627f1 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#33 0x0000555555760082 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#34 0x000055555574ca9f in tokio::task::core::Core<T>::transition_to_consumed (self=0x55555611c180)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/core.rs:106
#35 0x0000555555781de4 in tokio::task::harness::Harness<T,S>::do_cancel::{{closure}}::{{closure}} ()
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:363
#36 0x000055555575ce13 in core::ops::function::FnOnce::call_once () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
#37 0x000055555577da61 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=())
    at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:315
#38 0x00005555557a0998 in std::panicking::try::do_call (data=0x7fffffffd258 "\210\323\377\377\377\177\000")
    at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
#39 0x0000555555d04c5a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:80
#40 0x00005555557a03a4 in std::panicking::try (f=...) at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
#41 0x000055555577dab3 in std::panic::catch_unwind (f=...) at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
#42 0x0000555555781d8c in tokio::task::harness::Harness<T,S>::do_cancel::{{closure}} ()
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:361
#43 0x0000555555756958 in tokio::loom::std::causal_cell::CausalCell<T>::with_mut (self=0x55555611c180, f=...)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/loom/std/causal_cell.rs:41
#44 0x0000555555781b06 in tokio::task::harness::Harness<T,S>::do_cancel (self=..., res=...)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:359
#45 0x00005555557808b2 in tokio::task::harness::Harness<T,S>::cancel (self=..., from_queue=true)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:342
#46 0x000055555574bba2 in tokio::task::raw::cancel (ptr=0x55555611c150, from_queue=true)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/raw.rs:196
#47 0x0000555555c3d8b7 in tokio::task::raw::RawTask::cancel_from_queue (self=...)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/raw.rs:145
#48 0x0000555555c2c591 in tokio::task::Task<S>::shutdown (self=...)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/mod.rs:385
#49 0x0000555555c2bcc3 in tokio::task::queue::MpscQueues<S>::close_remote (self=0x55555610fcf0)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/queue.rs:266
#50 0x0000555555c2baef in tokio::task::queue::MpscQueues<S>::shutdown (self=0x55555610fcf0)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/queue.rs:224
#51 0x0000555555c65faa in <tokio::runtime::basic_scheduler::BasicScheduler<P> as core::ops::drop::Drop>::drop (self=0x7fffffffd710)
    at /home/bmwill/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/basic_scheduler.rs:297
#52 0x00005555557606d5 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#53 0x00005555557628a7 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#54 0x0000555555762ae1 in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#55 0x0000555555760e2a in core::ptr::real_drop_in_place () at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
#56 0x0000555555770153 in helloworld_client::main () at tonic-examples/src/helloworld/client.rs:45
```

</details>

As noted in one of the comments if you reverse the order of the fields (and thus the drop order so that the tonic client is dropped first) then the deadlock doesn't occur.

**Comment by carllerche** [comment]
Most likely a dup of #1886.

**Comment by carllerche** [comment]
Closing as this should be fixed in the latest released crate.
