### ISSUE TITLE
Runtime created by tokio::runtime::Builder could result in panic

### ISSUE THREAD

**Issue by doyoubi** [tokio-rs/tokio#2232]
## Version

```
└── tokio v0.2.11
    └── tokio-macros v0.2.4
```

```
[dependencies]
tokio = { version = "0.2.11", features = ["full"] }
```

## Platform

```
18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

## Description

The runtime created by runtime Builder could result in panic.

#### Code:
```
use tokio::net::TcpListener;
use tokio;
use std::error::Error;


fn main() -> Result<(), Box<dyn Error>> {
    let mut runtime = tokio::runtime::Builder::new().build()?;

    runtime.block_on(async {
        let _ = TcpListener::bind("127.0.0.1:8080").await;
    });
    Ok(())
}
```

#### Panic

```
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/io/driver/mod.rs:201:9
stack backtrace:
   0:        0x10db9c6c5 - backtrace::backtrace::libunwind::trace::h916301d0982371d3
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x10db9c6c5 - backtrace::backtrace::trace_unsynchronized::h0dc46500c034399e
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x10db9c6c5 - std::sys_common::backtrace::_print_fmt::h05abbd3e168095d3
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x10db9c6c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h12df651c925da5bc
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10dbb546e - core::fmt::write::h3a10d45dd3152bd1
                               at src/libcore/fmt/mod.rs:1052
   5:        0x10db985ab - std::io::Write::write_fmt::h607a243f7f923ba0
                               at src/libstd/io/mod.rs:1428
   6:        0x10db9e5ca - std::sys_common::backtrace::_print::h5fc8f0c245c69f35
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10db9e5ca - std::sys_common::backtrace::print::h1d6021302e2997ed
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10db9e5ca - std::panicking::default_hook::{{closure}}::h63fd0e7f144415ef
                               at src/libstd/panicking.rs:204
   9:        0x10db9e2ef - std::panicking::default_hook::hc75a14121581f988
                               at src/libstd/panicking.rs:224
  10:        0x10db9eca8 - std::panicking::rust_panic_with_hook::h3e4ce81305720511
                               at src/libstd/panicking.rs:470
  11:        0x10db9e842 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:        0x10dbb465f - core::panicking::panic_fmt::hff1d4819f9ea5de8
                               at src/libcore/panicking.rs:85
  13:        0x10dbb442a - core::option::expect_failed::he308bd920f2b557a
                               at src/libcore/option.rs:1191
  14:        0x10db5966c - core::option::Option<T>::expect::h0b474f050a83a6cb
                               at /rustc/c9290dceee2cb6b882b26ec6e294560e51ef0853/src/libcore/option.rs:347
  15:        0x10db01700 - tokio::io::driver::Handle::current::h4251a3b737d7ffd2
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/io/driver/mod.rs:201
  16:        0x10db3650c - tokio::io::registration::Registration::new::hb3cb60e8136c333e
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/io/registration.rs:69
  17:        0x10db45d4e - tokio::io::poll_evented::PollEvented<E>::new::h7bea40962311f84b
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/io/poll_evented.rs:178
  18:        0x10db2d757 - tokio::net::tcp::listener::TcpListener::new::hf8774f105e789d58
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/net/tcp/listener.rs:216
  19:        0x10db2d6d3 - tokio::net::tcp::listener::TcpListener::bind_addr::haedd0dd42a0cf290
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/net/tcp/listener.rs:97
  20:        0x10daf4d71 - tokio::net::tcp::listener::TcpListener::bind::{{closure}}::hf1b2877f50188807
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/net/tcp/listener.rs:81
  21:        0x10daf1da7 - <std::future::GenFuture<T> as core::future::future::Future>::poll::h7d9d288fb285cad1
                               at /rustc/c9290dceee2cb6b882b26ec6e294560e51ef0853/src/libstd/future.rs:43
  22:        0x10daf1acc - std::future::poll_with_tls_context::h07c4ab0642f79236
                               at /rustc/c9290dceee2cb6b882b26ec6e294560e51ef0853/src/libstd/future.rs:98
  23:        0x10daf11e7 - testtk::main::{{closure}}::hd6e5b91d1e4989e3
                               at src/main.rs:10
  24:        0x10daf1c74 - <std::future::GenFuture<T> as core::future::future::Future>::poll::h6d709c9a5445af06
                               at /rustc/c9290dceee2cb6b882b26ec6e294560e51ef0853/src/libstd/future.rs:43
  25:        0x10daf447b - tokio::runtime::shell::Shell::block_on::h6ab3da0d45c266d6
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/shell.rs:49
  26:        0x10daf3960 - tokio::runtime::Runtime::block_on::{{closure}}::h9d55a3877a3098a0
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:409
  27:        0x10daf45ae - tokio::runtime::context::enter::hbaa337baa60c91c6
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  28:        0x10daf141d - tokio::runtime::handle::Handle::enter::h461b91135bc8fcdf
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  29:        0x10daf3849 - tokio::runtime::Runtime::block_on::hd08fdf6585a9c5c4
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  30:        0x10daf0892 - testtk::main::h21f8b058931dbc33
                               at src/main.rs:9
  31:        0x10daf2e92 - std::rt::lang_start::{{closure}}::hea71dff4dafb6e35
                               at /rustc/c9290dceee2cb6b882b26ec6e294560e51ef0853/src/libstd/rt.rs:67
  32:        0x10db9e708 - std::rt::lang_start_internal::{{closure}}::h07b353cb71d2aaba
                               at src/libstd/rt.rs:52
  33:        0x10db9e708 - std::panicking::try::do_call::h3f6805a6fbce7574
                               at src/libstd/panicking.rs:303
  34:        0x10dba14cb - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  35:        0x10db9f06c - std::panicking::try::h24521c4e7932627d
                               at src/libstd/panicking.rs:281
  36:        0x10db9f06c - std::panic::catch_unwind::ha9e639d7a49a5285
                               at src/libstd/panic.rs:394
  37:        0x10db9f06c - std::rt::lang_start_internal::hbaf620607084552a
                               at src/libstd/rt.rs:51
  38:        0x10daf2e72 - std::rt::lang_start::h95f8bcd1a9cad053
                               at /rustc/c9290dceee2cb6b882b26ec6e294560e51ef0853/src/libstd/rt.rs:67
  39:        0x10daf0972 - testtk::main::h21f8b058931dbc33
```

**Comment by Darksonn** [comment]
You need to enable the IO driver:
```
use tokio::net::TcpListener;
use tokio;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let mut runtime = tokio::runtime::Builder::new().enable_io().build()?;

    runtime.block_on(async {
        let _ = TcpListener::bind("127.0.0.1:8080").await;
    });
    Ok(())
}
```
See [this](https://docs.rs/tokio/0.2/tokio/runtime/struct.Builder.html#method.enable_all).
