### ISSUE TITLE
Multithreaded runtime causes lot of single byte write syscalls

### ISSUE THREAD

**Issue by 95th** [tokio-rs/tokio#2287]
## Version

```
$ cargo tree | grep tokio
│   │   │   ├── tokio v0.2.13
│   │   │   │   └── tokio-macros v0.2.5
│   │   │   └── tokio-util v0.2.0
│   │   │       └── tokio v0.2.13 (*)
│   │   ├── tokio v0.2.13 (*)
│   │   ├── tokio v0.2.13 (*)
│   │   └── tokio-tls v0.3.0
│   │       └── tokio v0.2.13 (*)
│   ├── tokio v0.2.13 (*)
│   ├── tokio-tls v0.3.0 (*)
├── tokio v0.2.13 (*)
```

## Platform

```
$ uname -a
Linux lenovo 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Description

I am building a [bittorrent client](https://github.com/95th/btrs) using tokio. I was profiling system calls using strace and found that there are surprising (47000+) number of single byte write syscalls to a pipe. These writes seems to be issued from [here](https://github.com/tokio-rs/tokio/blob/master/tokio/src/signal/unix.rs#L214), though I could be wrong.

```
write(5, "\1", 1)
```

strace output:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 91.65    2.949181          62     47348           write
  5.08    0.163414          51      3179        23 futex
  1.51    0.048534         149       326        57 recvfrom
  1.42    0.045775          68       670           brk
  0.14    0.004531          82        55           sendto
  0.05    0.001466         293         5           munmap
  0.04    0.001325          29        46           sched_yield
  0.04    0.001202          17        72           read
  0.02    0.000622          13        49           mmap
  0.02    0.000536          32        17           close
  0.01    0.000344          57         6           epoll_ctl
  0.01    0.000276          92         3         3 connect
  0.01    0.000242          35         7           fcntl
  0.01    0.000182          11        16           fstat
  0.00    0.000138          46         3           socket
  0.00    0.000130          43         3           getsockopt
  0.00    0.000059          20         3           sigaltstack
  0.00    0.000043          43         1           setsockopt
  0.00    0.000041          41         1           getpeername
  0.00    0.000000           0        21           mprotect
  0.00    0.000000           0         5           rt_sigaction
  0.00    0.000000           0         1           rt_sigprocmask
  0.00    0.000000           0         1           ioctl
  0.00    0.000000           0        10        10 access
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         3           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           sysinfo
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           sched_getaffinity
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0        16         1 openat
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           epoll_create1
  0.00    0.000000           0         1           pipe2
  0.00    0.000000           0         2           prlimit64
  0.00    0.000000           0         4           getrandom
  0.00    0.000000           0        25        20 statx
------ ----------- ----------- --------- --------- ----------------
100.00    3.218041                 51907       114 total
```

As you can see, those writes consumes non-trivial amount of CPU time compared to the below.

If I switch the runtime to `basic_scheduler` or change core threads to 1, those writes go away:

strace:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 44.46    0.028987          42       683           brk
 28.21    0.018393          55       334        60 recvfrom
 11.04    0.007198          38       190           epoll_wait
  4.53    0.002953          51        58           sendto
  2.59    0.001691         121        14           munmap
  2.35    0.001533          11       138           sched_yield
  1.66    0.001082          29        37           mmap
  1.46    0.000949          38        25           write
  1.24    0.000806          40        20           close
  0.46    0.000301         100         3         3 connect
  0.45    0.000291          42         7           epoll_ctl
  0.38    0.000245          41         6           fcntl
  0.24    0.000154          10        16           fstat
  0.22    0.000144          48         3           socket
  0.19    0.000126          42         3           getsockopt
  0.14    0.000093          31         3           sigaltstack
  0.13    0.000088           1        73         2 read
  0.12    0.000077          77         1           shutdown
  0.06    0.000041          41         1           getpeername
  0.06    0.000041          41         1           setsockopt
  0.00    0.000000           0        19           mprotect
  0.00    0.000000           0         5           rt_sigaction
  0.00    0.000000           0         1           rt_sigprocmask
  0.00    0.000000           0         1           ioctl
  0.00    0.000000           0        10        10 access
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         1           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           sysinfo
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0        22           futex
  0.00    0.000000           0         1           sched_getaffinity
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0        15         1 openat
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           epoll_create1
  0.00    0.000000           0         1           pipe2
  0.00    0.000000           0         2           prlimit64
  0.00    0.000000           0         4           getrandom
  0.00    0.000000           0        25        20 statx
------ ----------- ----------- --------- --------- ----------------
100.00    0.065193                  1730        96 total
```

For now, I've switched the runtime to basic scheduler, but how do I stop those extraneous writes? Is that a bug? Any help is appreciated. Thanks

**Comment by carllerche** [comment]
They are most likely coming from mio in order to wake up a worker (a pipe is strategy used to wake a thread from `epoll_wait`).

Is it causing a perf problem? Otherwise, I wouldn't worry about it.

**Comment by 95th** [comment]
Yes. The download rate is higher (up to 10%) and CPU usage is lower when the extraneous writes are absent. 

I intend to have my library compete with libtorrent C++ library in terms of efficiency and be better in terms of safety.

Please let me know if there is something I can help with to fix this. Thanks

**Comment by carllerche** [comment]
I would recommend testing against #2273, see if that improves anything. If not, a minimal repro would be helpful to investigate.

**Comment by 95th** [comment]
I am getting following error with that branch:
```
thread 'main' panicked at 'not currently running on the Tokio runtime.', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: tokio::runtime::handle::Handle::current
  15: tokio::runtime::blocking::pool::spawn_blocking
  16: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
  17: <std::future::GenFuture<T> as core::future::future::Future>::poll
  18: <std::future::GenFuture<T> as core::future::future::Future>::poll
  19: <std::future::GenFuture<T> as core::future::future::Future>::poll
  20: <std::future::GenFuture<T> as core::future::future::Future>::poll
  21: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  22: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
  23: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
  24: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  25: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
  26: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
  27: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  28: <hyper::client::ResponseFuture as core::future::future::Future>::poll
  29: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
  30: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
  31: <std::future::GenFuture<T> as core::future::future::Future>::poll
  32: btrs::main::{{closure}}
  33: <std::future::GenFuture<T> as core::future::future::Future>::poll
  34: tokio::runtime::thread_pool::ThreadPool::block_on
  35: tokio::runtime::context::enter
  36: tokio::runtime::handle::Handle::enter
  37: btrs::main
  38: std::rt::lang_start::{{closure}}
  39: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  40: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  41: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  42: std::panicking::try
             at src/libstd/panicking.rs:270
  43: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  44: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  45: main
  46: __libc_start_main
  47: _start
```

**Comment by 95th** [comment]
Seems like reqwest/hyper won't work with that version

**Comment by hawkw** [comment]
You may need to patch `reqwest` and `hyper`'s `tokio` dependency?

**Comment by 95th** [comment]
Ok. I changed reqwest to use blocking.

The syscalls are about the same as before:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 93.95    2.952194          63     46773           write
  2.60    0.081685          49      1667        26 futex
  1.63    0.051249         157       327        57 recvfrom
  1.48    0.046358          70       664           brk
  0.15    0.004851          88        55           sendto
  0.07    0.002066         413         5           munmap
  0.05    0.001545          34        46           sched_yield
  0.03    0.000848          17        49           mmap
  0.01    0.000426          85         5           epoll_ctl
  0.01    0.000312         156         2         2 connect
  0.01    0.000288          19        15           close
  0.01    0.000259          52         5           fcntl
  0.00    0.000098          49         2           getsockopt
  0.00    0.000080          40         2           socket
  0.00    0.000064           5        12           fstat
  0.00    0.000020           7         3           sigaltstack
  0.00    0.000000           0        16           read
  0.00    0.000000           0        22           mprotect
  0.00    0.000000           0         5           rt_sigaction
  0.00    0.000000           0         1           rt_sigprocmask
  0.00    0.000000           0         1           ioctl
  0.00    0.000000           0        10        10 access
  0.00    0.000000           0         4           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           sched_getaffinity
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0        11           openat
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           epoll_create1
  0.00    0.000000           0         1           pipe2
  0.00    0.000000           0         2           prlimit64
  0.00    0.000000           0         3           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00    3.142343                 49714        95 total
```

**Comment by Darksonn** [comment]
If you use the blocking module in reqwest without fixing the `thread 'main' panicked at 'not currently running on the Tokio runtime.'` error, then reqwest is probably using the crates.io version of Tokio instead of the one you're trying to use. Consider using the [`[patch]`][1] section instead of directly pointing the dependency at git.

[1]: https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html

**Comment by ipetkov** [comment]
Is the application code in question registering interest in any OS signals? Whenever *any* signal is registered for the first time, tokio will register an OS signal handler and then perform the single byte write when said signal is received in order to wake any listeners.

Note that even after all signal listeners are dropped, the OS handler still continues to run (AFAIK there was no *geneeral* safe way to deregister a signal handler esp if other handlers are present, though if it is *really* a problem we could guard the pipe write somehow...)

**Comment by 95th** [comment]
@ipetkov the application is not using tokio `process` at all. There is no explicit registration for OS signals.

**Comment by 95th** [comment]
@Darksonn reqwest is only used for initial announce request. After that, I use simple tcp connections. So using blocking api for reqwest is fine IMO.

**Comment by Darksonn** [comment]
What's the status on this?

**Comment by 95th** [comment]
Hi sorry, I don't have a minimal repro for this. But in my application, I still have the same issue if I turn on the multithreaded runtime. For now, I am using single threaded RT.

**Comment by redjonzaci** [comment]
still needed?
