### ISSUE TITLE
panic in tokio::runtime::queue::Steal<T>::steal_into since 0.2.14

### ISSUE THREAD

**Issue by jeromegn** [tokio-rs/tokio#2364]
## Version

```
│   └── tokio v0.2.14
│       └── tokio-macros v0.2.5
│   │   ├── tokio v0.2.14 (*)
│   │   └── tokio-util v0.3.1
│   │       └── tokio v0.2.14 (*)
│   ├── tokio v0.2.14 (*)
│   ├── tokio v0.2.14 (*)
│   ├── tokio-rustls v0.13.0
│   │   ├── tokio v0.2.14 (*)
│   ├── tokio v0.2.14 (*)
│   ├── tokio-rustls v0.13.0 (*)
├── tokio v0.2.14 (*)
├── tokio-io-timeout v0.4.0
│   └── tokio v0.2.14 (*)
├── tokio-rustls v0.13.0 (*)
│   ├── tokio v0.2.14 (*)
│       ├── tokio v0.2.14 (*)
```

## Platform

Linux 4.18.0-21-generic

## Description

Started getting an occasional panic with 0.2.14:

```
assertion failed: `(left == right)`
  left: `71`,
 right: `72`

Thread 0
0   tokio      0xbbe227  [inlined] tokio::runtime::queue::Steal<T>::steal_into (queue.rs:324)
1   tokio      0xbbe227  [inlined] tokio::runtime::thread_pool::worker::Core::steal_work (worker.rs:436)
2   tokio      0xbbe227  tokio::runtime::thread_pool::worker::Context::run (worker.rs:285)
3   tokio      0xbae923  [inlined] tokio::runtime::thread_pool::worker::run::{{closure}} (worker.rs:264)
4   tokio      0xbae923  tokio::macros::scoped_tls::ScopedKey<T>::set (scoped_tls.rs:64)
5   tokio      0xbbd60e  tokio::runtime::thread_pool::worker::run (worker.rs:261)
6   tokio      0xbb27ab  [inlined] tokio::runtime::thread_pool::worker::Launch::launch::{{closure}} (worker.rs:240)
7   tokio      0xbb27ab  [inlined] tokio::runtime::blocking::task::BlockingTask<T>::poll (task.rs:38)
8   tokio      0xbb27ab  [inlined] tokio::runtime::task::core::Core<T>::poll::{{closure}} (core.rs:163)
9   tokio      0xbb27ab  tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut (unsafe_cell.rs:14)
10  tokio      0xbba1c3  [inlined] tokio::runtime::task::core::Core<T>::poll (core.rs:148)
11  tokio      0xbba1c3  [inlined] tokio::runtime::task::harness::Harness<T>::poll::{{closure}} (harness.rs:108)
12  core       0xbba1c3  [inlined] core::ops::function::FnOnce::call_once (function.rs:232)
13  std        0xbba1c3  std::panic::AssertUnwindSafe<T>::call_once (panic.rs:318)
14  std        0xbab739  std::panicking::try::do_call (panicking.rs:305)
15  <unknown>  0xd26227  __rust_maybe_catch_panic (lib.rs:86)
16  std        0xba31fe  [inlined] std::panicking::try (panicking.rs:281)
17  std        0xba31fe  [inlined] std::panic::catch_unwind (panic.rs:394)
18  tokio      0xba31fe  tokio::runtime::task::harness::Harness<T>::poll (harness.rs:84)
19  tokio      0xba17c8  [inlined] tokio::runtime::task::raw::RawTask::poll (raw.rs:66)
20  tokio      0xba17c8  [inlined] tokio::runtime::task::Notified<T>::run (mod.rs:169)
21  tokio      0xba17c8  tokio::runtime::blocking::pool::Inner::run (pool.rs:230)
22  tokio      0xbaca38  [inlined] tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}} (pool.rs:210)
23  tokio      0xbaca38  tokio::runtime::context::enter (context.rs:72)
24  tokio      0xba665f  [inlined] tokio::runtime::handle::Handle::enter (handle.rs:39)
25  tokio      0xba665f  [inlined] tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}} (pool.rs:209)
26  std        0xba665f  std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:129)
27  std        0xbab785  [inlined] std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
28  std        0xbab785  [inlined] std::panic::AssertUnwindSafe<T>::call_once (panic.rs:318)
29  std        0xbab785  std::panicking::try::do_call (panicking.rs:305)
30  <unknown>  0xd26227  __rust_maybe_catch_panic (lib.rs:86)
31  std        0xbb47fa  [inlined] std::panicking::try (panicking.rs:281)
32  std        0xbb47fa  [inlined] std::panic::catch_unwind (panic.rs:394)
33  std        0xbb47fa  [inlined] std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:474)
34  core       0xbb47fa  core::ops::function::FnOnce::call_once{{vtable.shim}} (function.rs:232)
35  alloc      0xd10e5f  alloc::boxed::Box<T>::call_once (boxed.rs:1015)
36  alloc      0xd25940  [inlined] alloc::boxed::Box<T>::call_once (boxed.rs:1015)
37  std        0xd25940  [inlined] std::sys_common::thread::start_thread (thread.rs:13)
38  std        0xd25940  std::sys::unix::thread::Thread::new::thread_start (thread.rs:80)
```

**Comment by nightmared** [comment]
Hello, I can also reproduce it on a project of my own:
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `100`,
 right: `117`', /home/nightmared/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.14/src/runtime/queue.rs:324:9
stack backtrace:
   0:     0x5616bf77ccc4 - backtrace::backtrace::libunwind::trace::h793a22e83bc43d9e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x5616bf77ccc4 - backtrace::backtrace::trace_unsynchronized::h370c30473f487be3
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x5616bf77ccc4 - std::sys_common::backtrace::_print_fmt::h012e9536cfcc40eb
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5616bf77ccc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48e5b57dc6d7049b
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5616bf79e0fc - core::fmt::write::h598d78f93632c19a
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5616bf777483 - std::io::Write::write_fmt::h610a2742fd04e519
                               at src/libstd/io/mod.rs:1427
   6:     0x5616bf77f4f5 - std::sys_common::backtrace::_print::h3c838a33b0edd973
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5616bf77f4f5 - std::sys_common::backtrace::print::hfcdbd5002d0223aa
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5616bf77f4f5 - std::panicking::default_hook::{{closure}}::h0bb791a887b6b7ea
                               at src/libstd/panicking.rs:198
   9:     0x5616bf77f242 - std::panicking::default_hook::hcd881bd8e0ac0eb0
                               at src/libstd/panicking.rs:218
  10:     0x5616bf77fb52 - std::panicking::rust_panic_with_hook::h4c18c33892d24d84
                               at src/libstd/panicking.rs:511
  11:     0x5616bf77f73b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x5616bf77f6ab - std::panicking::begin_panic_fmt::hbf60b0ac1f798742
                               at src/libstd/panicking.rs:373
  13:     0x5616bf764480 - tokio::runtime::queue::Steal<T>::steal_into::h704a6fd8bd741186
  14:     0x5616bf74c941 - tokio::runtime::thread_pool::worker::Context::run::h77ec58de517d228d
  15:     0x5616bf753d63 - tokio::macros::scoped_tls::ScopedKey<T>::set::hdea1b0f655ea0439
  16:     0x5616bf74c5cb - tokio::runtime::thread_pool::worker::run::h6601bd09bf9f5f33
  17:     0x5616bf75c5fb - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h32e29a82f9f7ac64
  18:     0x5616bf752365 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0ff1bbb32d4c53ff
  19:     0x5616bf765676 - tokio::runtime::task::harness::Harness<T,S>::poll::h16755979f41e9133
  20:     0x5616bf74fa57 - tokio::runtime::blocking::pool::Inner::run::hf5c93667ae5b02da
  21:     0x5616bf747e18 - tokio::runtime::context::enter::h801786fe775e97e9
  22:     0x5616bf75252f - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ae6b76f46f31f9c
  23:     0x5616bf75d272 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf61f70123107b5ac
  24:     0x5616bf7714ef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h000a4e6e762bbe02
                               at /rustc/7ceebd98c6a15ae30e772eebb676b63ffa1a8122/src/liballoc/boxed.rs:1017
  25:     0x5616bf7822fd - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hee0ca0086c0584cb
                               at /rustc/7ceebd98c6a15ae30e772eebb676b63ffa1a8122/src/liballoc/boxed.rs:1017
  26:     0x5616bf7822fd - std::sys_common::thread::start_thread::h68bf20ee983bdeeb
                               at src/libstd/sys_common/thread.rs:13
  27:     0x5616bf7822fd - std::sys::unix::thread::Thread::new::thread_start::h157c235aed8601f7
                               at src/libstd/sys/unix/thread.rs:80
  28:     0x7fbab2d61f27 - start_thread
                               at /builddir/glibc-2.30/nptl/pthread_create.c:479
  29:     0x7fbab2c73e0f - __GI___clone
  30:                0x0 - <unknown>
```
When using wrk to test my project it crashes consistently with this error message.

**Comment by nightmared** [comment]
#2362 seems to fix it for me ;)

**Comment by jeromegn** [comment]
Can confirm #2362 fixes it.

**Comment by carllerche** [comment]
0.2.15 is out w/ a fix. Sorry about that.
