### ISSUE TITLE
time::delay_for panics with cryptic message if Duration is too high

### ISSUE THREAD

**Issue by paulocsanz** [tokio-rs/tokio#2408]
Hey, this bug was found first by messing with warp, so the issue seanmonstar/warp#539 was made to understand it better.

@LucioFranco got the minimized tokio example https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f0f684173d7dbd78a3780f2be8311798

```rust
#[tokio::main]
async fn main() {
    tokio::time::delay_for(std::time::Duration::from_secs(10000000000)).await;
}
```

It has a fairly weird message, maybe an `assert!` with a message explaining the limit would solve it. Because it made it fairly hard to understand the crash (I was miscalculating the duration). Since nobody would actually wait that long. And if they want, they can call it sequentially.

Panic:
```thread 'main' panicked at 'timer error: the timer is shutdown, must be called from the context of Tokio runtime', /home/no/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.16/src/time/delay.rs:96:23```

**Comment by paulocsanz** [comment]
I've investigated a bit, the problem is that `time::driver::entry` has only one `ERROR` state, it would require a bit of rework to allow for other errors.

**Comment by MikailBag** [comment]
I got this panic running tokio test suite:

```
---- no_out_of_bounds_close_to_max stdout ----
thread 'no_out_of_bounds_close_to_max' panicked at 'timer error: the timer is shutdown, must be called from the context of Tokio runtime', tokio/src/time/delay.rs:96:23
stack backtrace:
   0:     0x55f4e592f5d4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55f4e592f5d4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55f4e592f5d4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55f4e592f5d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55f4e595090c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55f4e5836975 - std::io::Write::write_fmt::h0925d1b2b49a7c6d
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/io/mod.rs:1426
   6:     0x55f4e5929d11 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h8750380b9d499e97
                               at src/libstd/io/impls.rs:156
   7:     0x55f4e5931915 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   8:     0x55f4e5931915 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   9:     0x55f4e5931915 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
  10:     0x55f4e59315a8 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:221
  11:     0x55f4e5931f7a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  12:     0x55f4e5931b60 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  13:     0x55f4e5931adb - std::panicking::begin_panic_fmt::h3f391831d1286dec
                               at src/libstd/panicking.rs:334
  14:     0x55f4e58c6ac2 - <tokio::time::delay::Delay as core::future::future::Future>::poll::h2eb86b32d587f03a
                               at tokio/src/time/delay.rs:96
  15:     0x55f4e581508d - std::future::poll_with_tls_context::h355556079f49ccec
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/future.rs:98
  16:     0x55f4e583553c - time_delay::no_out_of_bounds_close_to_max::{{closure}}::h4424cacca432a104
                               at tokio/tests/time_delay.rs:171
  17:     0x55f4e5815bea - <std::future::GenFuture<T> as core::future::future::Future>::poll::heb1ae33bc54dcaf3
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/future.rs:43
  18:     0x55f4e58291ed - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::hed93ba4da7a7f563
                               at /home/mb/projects/tokio/tokio/src/runtime/basic_scheduler.rs:131
  19:     0x55f4e580fb14 - tokio::coop::budget::{{closure}}::hdb6d0c99832ed224
                               at /home/mb/projects/tokio/tokio/src/coop.rs:97
  20:     0x55f4e581c255 - std::thread::local::LocalKey<T>::try_with::h892f083e5ae2dd79
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/local.rs:262
  21:     0x55f4e5818ba7 - std::thread::local::LocalKey<T>::with::hf91416fc494125c6
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/local.rs:239
  22:     0x55f4e5825f18 - tokio::coop::budget::h2c1e0b88b93384e7
                               at /home/mb/projects/tokio/tokio/src/coop.rs:79
  23:     0x55f4e5825f18 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h72a08e7e12ba31c4
                               at /home/mb/projects/tokio/tokio/src/runtime/basic_scheduler.rs:131
  24:     0x55f4e582b987 - tokio::runtime::basic_scheduler::enter::{{closure}}::h8bb22cd4fc9697b1
                               at /home/mb/projects/tokio/tokio/src/runtime/basic_scheduler.rs:213
  25:     0x55f4e580d160 - tokio::macros::scoped_tls::ScopedKey<T>::set::hfb5d182bf51df280
                               at /home/mb/projects/tokio/tokio/src/macros/scoped_tls.rs:64
  26:     0x55f4e582a5cb - tokio::runtime::basic_scheduler::enter::h4d3bd708d4799ab1
                               at /home/mb/projects/tokio/tokio/src/runtime/basic_scheduler.rs:213
  27:     0x55f4e5822d57 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h97e31158d5b09670
                               at /home/mb/projects/tokio/tokio/src/runtime/basic_scheduler.rs:123
  28:     0x55f4e582c691 - tokio::runtime::Runtime::block_on::{{closure}}::h2e7a94838311de28
                               at /home/mb/projects/tokio/tokio/src/runtime/mod.rs:417
  29:     0x55f4e58212dc - tokio::runtime::context::enter::h8e51a0895821dd4a
                               at /home/mb/projects/tokio/tokio/src/runtime/context.rs:72
  30:     0x55f4e5810480 - tokio::runtime::handle::Handle::enter::h8ff2848659e0b56f
                               at /home/mb/projects/tokio/tokio/src/runtime/handle.rs:39
  31:     0x55f4e582c2b3 - tokio::runtime::Runtime::block_on::h708e4581225b2f01
                               at /home/mb/projects/tokio/tokio/src/runtime/mod.rs:414
  32:     0x55f4e5811627 - time_delay::no_out_of_bounds_close_to_max::h0b7c038188160ee8
                               at tokio/tests/time_delay.rs:168
  33:     0x55f4e583543a - time_delay::no_out_of_bounds_close_to_max::{{closure}}::hd885ec724e5bde96
                               at tokio/tests/time_delay.rs:168
  34:     0x55f4e581e68e - core::ops::function::FnOnce::call_once::h8166f9ad12fec525
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  35:     0x55f4e58416af - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h475aad1d2c31134b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  36:     0x55f4e5938cd7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  37:     0x55f4e585c4c1 - std::panicking::try::hd62f6e4f8420ceba
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  38:     0x55f4e585c4c1 - std::panic::catch_unwind::hc2e8046ccc21e1ce
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  39:     0x55f4e585c4c1 - test::run_test_in_process::h995368d8855d316e
                               at src/libtest/lib.rs:539
  40:     0x55f4e585c4c1 - test::run_test::run_test_inner::{{closure}}::h9d340cbc9c948d1d
                               at src/libtest/lib.rs:452
  41:     0x55f4e5835de6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h263f57609c58fd78
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/backtrace.rs:129
  42:     0x55f4e583a3b6 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::he48f3c390b307d2a
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:475
  43:     0x55f4e583a3b6 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h25632fa6cd6e735b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:318
  44:     0x55f4e583a3b6 - std::panicking::try::do_call::h46edd85e35bab050
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:305
  45:     0x55f4e5938cd7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  46:     0x55f4e583af16 - std::panicking::try::h689d027f9de46764
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  47:     0x55f4e583af16 - std::panic::catch_unwind::h007d6d1ca365ec57
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  48:     0x55f4e583af16 - std::thread::Builder::spawn_unchecked::{{closure}}::h7348caa4b4241ad9
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:474
  49:     0x55f4e583af16 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1c0e48707c1ce7ba
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  50:     0x55f4e592630f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he3e3bc9932f56404
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  51:     0x55f4e5938240 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0d82364c11057a62
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  52:     0x55f4e5938240 - std::sys_common::thread::start_thread::h6cf2238254b521b3
                               at src/libstd/sys_common/thread.rs:13
  53:     0x55f4e5938240 - std::sys::unix::thread::Thread::new::thread_start::he70a06005b4d03f8
                               at src/libstd/sys/unix/thread.rs:80
  54:     0x7fc5b46e9669 - start_thread
  55:     0x7fc5b45f7323 - clone
  56:                0x0 - <unknown>

```

**Comment by LucioFranco** [comment]
cc @carllerche

**Comment by federico-terzi** [comment]
I agree with @paulocsanz, an `assert!()` call could be a good starting point to make the error clearer

**Comment by MikailBag** [comment]
I can't reproduce. E.g. 
```rust
#[tokio::test]
async fn foo() {
    let delay = tokio::time::delay_for(std::time::Duration::from_micros(u64::max_value()));

    delay.await;
}
```
fails with
```
thread 'temporary' panicked at 'timer error: timer duration exceeds maximum duration', tokio/src/time/delay.rs:115:23
```
Manual runtime creation does not change panic text.

Looking at source code, it also seems that behavior is correct now:
tokio::time::wheel::Wheel::insert returns `InsertError::Invalid`,
which is propagated to `Error::Invalid` by tokio::time::driver::Driver::add_entry,
resulting in correct panic message.

**Comment by Darksonn** [comment]
Ah, it must have been fixed then.

**Comment by MikailBag** [comment]
Update: I was able to reproduce this on 0.2.22, latest stable release. So, next release should fix this.
