### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.remaining() >= dst.len()'

### ISSUE THREAD

**Issue by yuya008** [tokio-rs/tokio#2620]
**Version**
```
❯ cargo tree | grep tokio                                                                                                        proxy-rs/git/master
└── tokio v0.2.21
    └── tokio-macros v0.2.5
❯
```
**Platform**
Linux xs103192226168 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description**
Sorry, this stack error, I can not understand, because there is no information of my code, please have a look.
Here is my code repository: https://github.com/yuya008/proxy-rs

The following is panic information
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.remaining() >= dst.len()', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/macros/mod.rs:34:9
stack backtrace:
   0:     0x56289e4e8a24 - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x56289e4e8a24 - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x56289e4e8a24 - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x56289e4e8a24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x56289e50abfc - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x56289e4e2293 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x56289e4eb0b5 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56289e4eb0b5 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56289e4eb0b5 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x56289e4eadf2 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x56289e4eb712 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x56289e4eb2fb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x56289e509fe1 - core::panicking::panic_fmt::h1ac71ad045d55416
                               at src/libcore/panicking.rs:111
  13:     0x56289e509f2d - core::panicking::panic::h57854ec308e1f8ab
                               at src/libcore/panicking.rs:54
  14:     0x56289e261acc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6bacbc5824b69a52
  15:     0x56289e26e224 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf55c1c20ee0139b9
  16:     0x56289e252aff - tokio::runtime::task::harness::Harness<T,S>::poll::ha4902cd6d6509727
  17:     0x56289e35fae9 - std::thread::local::LocalKey<T>::with::hdc485a04c100134a
  18:     0x56289e367aa2 - tokio::runtime::thread_pool::worker::Context::run_task::he82c3d9522bdca20
  19:     0x56289e3674a9 - tokio::runtime::thread_pool::worker::Context::run::h2da48de26f8d1e0a
  20:     0x56289e358a03 - tokio::macros::scoped_tls::ScopedKey<T>::set::hb3659a0d5c473f1c
  21:     0x56289e366bab - tokio::runtime::thread_pool::worker::run::h962bb15e6f393733
  22:     0x56289e35dcc9 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h085c88bf08dd99f7
  23:     0x56289e36df02 - tokio::runtime::task::harness::Harness<T,S>::poll::hc8509e47d544e7de
  24:     0x56289e35abb7 - tokio::runtime::blocking::pool::Inner::run::hd86b2315b79bc51c
  25:     0x56289e357898 - tokio::runtime::context::enter::h6aed929b2673f135
  26:     0x56289e35180f - std::sys_common::backtrace::__rust_begin_short_backtrace::h3867e28d600e4185
  27:     0x56289e360082 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h68a0d09cb9604a9e
  28:     0x56289e4ee41a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1f1fac7de7dd9691
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  29:     0x56289e4ee41a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha031f48633a6af54
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  30:     0x56289e4ee41a - std::sys::unix::thread::Thread::new::thread_start::h241864caf436e182
                               at src/libstd/sys/unix/thread.rs:87
  31:     0x7fdef73f4ea5 - start_thread
  32:     0x7fdef6afb8dd - __clone
  33:                0x0 - <unknown>
```

**Comment by yuya008** [comment]
@carllerche I added the information

**Comment by yuya008** [comment]
It's a bug in my own code

**Comment by J-Cake** [comment]
What was the buf? I'm experiencing this myself, and would like to know what caused it, in an effort to debug it
