### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'queue not empty'

### ISSUE THREAD

**Issue by stuhood** [tokio-rs/tokio#2877]
Hey folks!

**Version**
```
 "tokio 0.2.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "tokio-connect 0.1.0 (git+https://github.com/pantsbuild/tokio-connect?rev=f7ad1ca437973d6e24037ac6f7d5ef1013833c0b)",
 "tokio-io 0.1.13 (registry+https://github.com/rust-lang/crates.io-index)",
 "tokio-macros 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "tokio-rustls 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "tokio-util 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
```

**Platform**

Ubuntu 18.04 (possibly others), although afaik we have not had a repro on OSX.

**Description**

This is not a particularly descriptive bug report, and I apologize: am happy to follow up to try to get more details, but wanted to get it on the books in case this demonstrates a case that "should be impossible".

Sometimes when shutting down (generally due to an early exit, which might mean that there was other work scheduled, but it was aborted), we have observed:
```
thread 'tokio-runtime-worker' panicked at 'queue not empty', /travis/home/.cache/pants/rust/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.20/src/runtime/queue.rs:450:13
stack backtrace:
   0:     0x7f8bf3029474 - <unknown>
   1:     0x7f8bf304ee9c - <unknown>
   2:     0x7f8bf3022847 - <unknown>
   3:     0x7f8bf302bd55 - <unknown>
   thread 'tokio-runtime-worker' panicked at 'queue not empty', /travis/home/.cache/pants/rust/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.20/src/runtime/queue.rs:450:13
thread 'tokio-runtime-worker' panicked at 'queue not empty', /travis/home/.cache/pants/rust/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.20/src/runtime/queue.rs:450:13
4:     0x7f8bf302ba41 - <unknown>
   5:     0x7f8bf302c39a - <unknown>
   6:     0x7f8bf2f3806e - <unknown>
   7:     0x7f8bf2f3dc75 - <unknown>
   8:     0x7f8bf2f50359 - <unknown>
   9:     0x7f8bf2f381b4 - <unknown>
  10:     0x7f8bf3034c57 - <unknown>
  11:     0x7f8bf2f4b8f2 - <unknown>
  12:     0x7f8bf2f36436 - <unknown>
  13:     0x7f8bf2f38105 - <unknown>
  14:     0x7f8bf3034c57 - <unknown>
  15:     0x7f8bf2f3868a - <unknown>
  16:     0x7f8bf301b3ef - <unknown>
  17:     0x7f8bf3033e40 - <unknown>
  18:     0x7f8bfd55b6db - start_thread
  19:     0x7f8bfcadf88f - __clone
  20:                0x0 - <unknown>
stack backtrace:
   0:     0x7f8bf3029474 - <unknown>
   1:     0x7f8bf304ee9c - <unknown>
   2:     0x7f8bf3022847 - <unknown>
   3:     0x7f8bf302bd55 - <unknown>
   4:     0x7f8bf302ba41 - <unknown>
   5:     0x7f8bf302c39a - <unknown>
   6:     0x7f8bf2f3806e - <unknown>
   7:     0x7f8bf2f3dc75 - <unknown>
   8:     0x7f8bf2f50359 - <unknown>
   9:     0x7f8bf2f381b4 - <unknown>
  10:     0x7f8bf3034c57 - <unknown>
  11:     0x7f8bf2f4b8f2 - <unknown>
  12:     0x7f8bf2f36436 - <unknown>
  13:     0x7f8bf2f38105 - <unknown>
  14:     0x7f8bf3034c57 - <unknown>
  15:     0x7f8bf2f3868a - <unknown>
  16:     0x7f8bf301b3ef - <unknown>
  17:     0x7f8bf3033e40 - <unknown>
  18:     0x7f8bfd55b6db - start_thread
  19:     0x7f8bfcadf88f - __clone
  20:                0x0 - <unknown>
stack backtrace:
   0:     0x7f8bf3029474 - <unknown>
   1:     0x7f8bf304ee9c - <unknown>
   2:     0x7f8bf3022847 - <unknown>
   3:     0x7f8bf302bd55 - <unknown>
   4:     0x7f8bf302ba41 - <unknown>
   5:     0x7f8bf302c39a - <unknown>
   6:     0x7f8bf2f3806e - <unknown>
   7:     0x7f8bf2f3dc75 - <unknown>
   8:     0x7f8bf2f50359 - <unknown>
   9:     0x7f8bf2f381b4 - <unknown>
  10:     0x7f8bf3034c57 - <unknown>
  11:     0x7f8bf2f4b8f2 - <unknown>
  12:     0x7f8bf2f36436 - <unknown>
  13:     0x7f8bf2f38105 - <unknown>
  14:     0x7f8bf3034c57 - <unknown>
  15:     0x7f8bf2f3868a - <unknown>
  16:     0x7f8bf301b3ef - <unknown>
  17:     0x7f8bf3033e40 - <unknown>
  18:     0x7f8bfd55b6db - start_thread
  19:     0x7f8bfcadf88f - __clone
  20:                0x0 - <unknown>
```

We have debug symbols enabled in release mode, but even in debug mode the stacktrace is not much more detailed for some reason.

**Comment by Darksonn** [comment]
I asked around on our discord, but nobody had any immediate guesses.

**Comment by stuhood** [comment]
We haven't seen this one recently. Closing.
