### ISSUE TITLE
old version api support(version 0.2-0.3)

### ISSUE THREAD

**Issue by zhuxiujia** [tokio-rs/tokio#3006]
hyper (tokio 0.3) or other lib  can not be run!
```rust
#[tokio::test]
pub async fn test_hyper() {
let make_svc = hyper::service::make_service_fn(|_conn| {
        async { Ok::<_, Infallible>(hyper::service::service_fn(hello)) }
    });
    let addr = ([0, 0, 0, 0], 8000).into();
    let server = hyper::Server::bind(&addr).serve(make_svc);
    println!("Listening on http://{}", addr);
    server.await.unwrap();
}
```
```rust
there is no reactor running, must be called from the context of Tokio runtime
thread 'test_hyper' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/driver/mod.rs:202:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
   3: core::option::Option<T>::expect
             at /Users/zhuxiujie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:333
   4: tokio::io::driver::Handle::current
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/driver/mod.rs:201
   5: tokio::io::registration::Registration::new_with_ready
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/registration.rs:106
   6: tokio::io::poll_evented::PollEvented<E>::new_with_ready
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/poll_evented.rs:206
   7: tokio::io::poll_evented::PollEvented<E>::new
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/poll_evented.rs:178
   8: tokio::net::tcp::listener::TcpListener::from_std
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/net/tcp/listener.rs:268
   9: hyper::server::tcp::AddrIncoming::from_std
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/server/tcp.rs:33
  10: hyper::server::tcp::AddrIncoming::new
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/server/tcp.rs:29
  11: hyper::server::Server<hyper::server::tcp::AddrIncoming,()>::bind
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/server/mod.rs:123
  12: example::test_hyper::{{closure}}
             at ./src/main.rs:266
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/zhuxiujie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  14: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/park/thread.rs:263
  15: tokio::coop::with_budget::{{closure}}
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/coop.rs:121
  16: std::thread::local::LocalKey<T>::try_with
             at /Users/zhuxiujie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:265
  17: std::thread::local::LocalKey<T>::with
             at /Users/zhuxiujie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:241
  18: tokio::coop::with_budget
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/coop.rs:114
  19: tokio::coop::budget
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/coop.rs:98
  20: tokio::park::thread::CachedParkThread::block_on
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/park/thread.rs:263
  21: tokio::runtime::enter::Enter::block_on
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/runtime/enter.rs:151
  22: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/runtime/thread_pool/mod.rs:80
  23: tokio::runtime::Runtime::block_on
             at /Users/zhuxiujie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/runtime/mod.rs:422
  24: example::test_hyper
             at ./src/main.rs:251
  25: example::test_hyper::{{closure}}
             at ./src/main.rs:251
  26: core::ops::function::FnOnce::call_once
             at /Users/zhuxiujie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  27: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: test failed, to rerun pass '-p example --bin example'
```

**Comment by Darksonn** [comment]
This can be done using the [`tokio-compat-02`][1] crate. In particular, you can check out the [hyper server][2] example.


[1]: https://docs.rs/tokio-compat-02/0.1.1/tokio_compat_02/
[2]: https://github.com/LucioFranco/tokio-compat-02/blob/main/examples/hyper_server.rs
