### ISSUE TITLE
timer::Delay is not working with current_thread executor

### ISSUE THREAD

**Issue by losfair** [tokio-rs/tokio#305]
This panics with `Error(Shutdown)`:

```rust
extern crate tokio;
extern crate futures;

use std::time::{Instant, Duration};
use futures::Future;

fn delay() -> impl Future<Item = (), Error = ()> {
    tokio::timer::Delay::new(
        Instant::now() + Duration::from_millis(500)
    ).map(|_| {
        println!("OK");
        ()
    }).map_err(|e| {
        panic!("{:?}", e);
    })
}

fn main() {
    //tokio::run(delay());
    tokio::executor::current_thread::block_on_all(delay()).unwrap();
}
```

Backtrace:

```
thread 'main' panicked at 'Error(Shutdown)', src/main.rs:14:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: tokio_bug::delay::{{closure}}
             at src/main.rs:14
   7: <core::result::Result<T, E>>::map_err
             at /checkout/src/libcore/result.rs:500
   8: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/map_err.rs:34
   9: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  10: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  11: futures::task_impl::std::set
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/std/mod.rs:78
  12: <futures::task_impl::Spawn<T>>::enter
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  13: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  14: <tokio::executor::current_thread::Entered<'a, P>>::block_on::{{closure}}
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:445
  15: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:657
  16: tokio::executor::current_thread::CurrentRunner::set_spawn
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:689
  17: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:656
  18: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:290
  19: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:244
  20: <tokio::executor::current_thread::Borrow<'a, U>>::enter
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:655
  21: <tokio::executor::current_thread::Entered<'a, P>>::block_on
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:444
  22: <tokio::executor::current_thread::CurrentThread<P>>::block_on
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:340
  23: tokio::executor::current_thread::block_on_all
             at /home/zhy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:256
  24: tokio_bug::main
             at src/main.rs:20
  25: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  26: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  27: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  28: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  29: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  30: main
  31: __libc_start_main
  32: _start
```

If `tokio::run` is used instead of `tokio::executor::current_thread::block_on_all`, the code works fine.

**Comment by arthurprs** [comment]
I think there's a ton of thread_local_magic/binding going on. I'm finding it quite hard to make anything other than of tokio::run and tokio::spawn work right now.

**Comment by carllerche** [comment]
#235 represents being able to create a single threaded runtime.

@arthurprs well, not having it be documented doesn't help either.

[This](https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/mod.rs#L231-L240) is what you do to setup the context.

**Comment by carllerche** [comment]
I'm going to close this issue as I think #235 already covers this.
