### ISSUE TITLE
Fix ping_pong_saturation test

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3305]
I got the following panic when running the test suite:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:thread '38tokio-runtime-worker
' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054thread ':tokio-runtime-worker38' panicked at '
called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())called `Result::unwrap()` on an `Err` value: SendError(())', ', tokio/tests/rt_common.rstokio/tests/rt_common.rs::10541054::3838

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(())', tokio/tests/rt_common.rs:1054:38
test threaded_scheduler_4_threads::ping_pong_saturation ... ok
```

**Comment by blasrodri** [comment]
I found the issue only on the `threaded_scheduler_4_threads`.
This workaround fixes it. Not sure if this is what you had in min @Darksonn 

```diff
diff --git a/tokio/tests/rt_common.rs b/tokio/tests/rt_common.rs
index 66e6f2c1..8047034a 100644
--- a/tokio/tests/rt_common.rs
+++ b/tokio/tests/rt_common.rs
@@ -1024,6 +1024,7 @@ rt_test! {
         use tokio::sync::mpsc;
 
         const NUM: usize = 100;
+        const NUM_ITERATIONS: usize = 1_000;
 
         let rt = rt();
 
@@ -1032,6 +1033,7 @@ rt_test! {
 
             // Spawn a bunch of tasks that ping ping between each other to
             // saturate the runtime.
+
             for _ in 0..NUM {
                 let (tx1, mut rx1) = mpsc::unbounded_channel();
                 let (tx2, mut rx2) = mpsc::unbounded_channel();
@@ -1042,14 +1044,16 @@ rt_test! {
 
                     tx1.send(()).unwrap();
 
-                    loop {
+                    for i in 0..=NUM_ITERATIONS {
                         rx2.recv().await.unwrap();
-                        tx1.send(()).unwrap();
+                        if i < NUM_ITERATIONS {
+                            tx1.send(()).unwrap();
+                        }
                     }
                 });
 
                 task::spawn(async move {
-                    loop {
+                    for _ in 0..=NUM_ITERATIONS {
                         rx1.recv().await.unwrap();
                         tx2.send(()).unwrap();
                     }
@@ -1068,6 +1072,8 @@ rt_test! {
                 }
             });
             handle.await.unwrap();
+            std::thread::sleep(std::time::Duration::from_millis(500));
+
         });
     }
 }
```

**Comment by Darksonn** [comment]
The purpose of the test is to verify that the task we spawn at the end and store in `handle` can run at all next to the ping-pong tasks, but this would change no longer test for that because, even if it can't, they will all exit after `NUM_ITERATIONS`, at which point `handle` _can_ run as there are no other tasks. Also, we should not be using `sleep` to wait for tasks to exit, that's fragile.

For example, if we introduce an `running` of type `Arc<AtomicBool>` to signal exit, and change one task to this:
```Rust
task::spawn(async move {
    spawned_tx.send(()).unwrap();

    while running.load(Ordering::Relaxed) {
        tx1.send(()).unwrap();
        rx2.recv().await.unwrap();
    }

    // Close the channel and wait for the other task to exit.
    drop(tx1);
    assert!(rx2.recv().await.is_none());
});
```
and change the other task to this:
```Rust
task::spawn(async move {
    while rx1.recv().await.is_some() {
        tx2.send(()).unwrap();
    }
});
```
Then we should be able to make them all exit by setting the boolean to `false`. Then if we put the `JoinHandle`s in a vector, we can join them all after `handle.await`.

**Comment by blasrodri** [comment]
Thanks! I'll make a PR.
