### ISSUE TITLE
debug_assert triggered in tokio_threadpool

### ISSUE THREAD

**Issue by Marwes** [tokio-rs/tokio#342]
Working on an upgrade of https://github.com/alexcrichton/tokio-signal and encountered this assertion triggered. This might just be something I am doing wrong but I haven't been able to figure out what yet.

A notable thing is that both `tokio` and `tokio_core` are used simultaneously in the tests that reproduces this.

Reproduces from this branch https://github.com/Marwes/tokio-signal/tree/tokio_threadpool_panic by running `RUST_BACKTRACE=1 cargo test` (it can take a few tries).

```
RUST_BACKTRACE=1 cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.28 secs
     Running target/debug/deps/tokio_signal-8dd3555875775ac7

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/signal-856f403b5d339b50

running 6 tests
test drop_then_get_a_signal ... ok
test simple ... ok
test notify_both ... ok
test twice ... ok
thread 'tokio-runtime-worker-4' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(WorkerId(11))`', /home/Mar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.3/src/pool/backup.rs:102:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: tokio_threadpool::pool::backup::Backup::start
             at /home/Mar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.3/src/pool/backup.rs:102
   7: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at /home/Mar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.3/src/pool/mod.rs:387
```

**Comment by carllerche** [comment]
I'm investigating this and it looks pretty strange. I'm wondering if it is due to how tokio-signal works with regards to threads.

**Comment by carllerche** [comment]
Ok, I have tracked down the bug. It is occurs when two separate threadpools interact (a future on one threadpool notifies a future on another threadpool).

It should be a relatively simple fix once I have a test.
