### ISSUE TITLE
assertion failed: !state.is_pushed()

### ISSUE THREAD

**Issue by Twey** [tokio-rs/tokio#387]
I've hit this assertion when trying to write some code that interfaces between Rust (with tokio) and C++ (with callbacks). Essentially I've some code that spins up an accepting loop on another thread and then a binding part that communicates with the accepting thread, sending it a `oneshot::Sender` that will be passed the next `TcpStream`, giving me a `Future<Item=tokio::net::TcpStream>`. However, when I run this code, it sometimes triggers an assertion deep in `tokio-threadpool` when one of the threads starts up. I've managed to reproduce the error in a minimal example that doesn't involve the network at all.

The important parts seem to be:
— running `tokio::run` twice in parallel
— receiving from a channel (`futures::sync::oneshot` works, as does `futures::sync::mpsc`)
— having one thread own the sender (it doesn't have to actually send, and in fact can just immediately drop it) while the other owns the receiver

MWE:
```rust
extern crate tokio;
extern crate futures;
extern crate env_logger;

use futures::{future, Future};

fn main() {
    env_logger::init();
    let (s, r) = futures::sync::oneshot::channel();
    std::thread::spawn(|| tokio::run(r.map_err(drop)));
    tokio::run(future::lazy(|| { drop(s); future::empty() }));
}
```
Output:
```
[twey@uruz /tmp/mwe]$ RUST_BACKTRACE=full RUST_LOG=trace ./target/debug/main
TRACE 2018-06-01T15:54:44Z: mio::poll: registering with poller
TRACE 2018-06-01T15:54:44Z: mio::poll: registering with poller
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::builder: build; num-workers=8
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::builder: build; num-workers=8
DEBUG 2018-06-01T15:54:44Z: tokio_reactor::background: starting background reactor
DEBUG 2018-06-01T15:54:44Z: tokio_reactor::background: starting background reactor
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::sender: execute; count=1
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::sender: execute; count=1
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool: submit to existing worker; idx=7; state=worker::State { lifecycle: Shutdown, is_pushed: true }
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool: submit to existing worker; idx=7; state=worker::State { lifecycle: Shutdown, is_pushed: true }
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool: shutdown; state=pool::State { lifecycle: Running, num_futures: 1 }
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool:   -> transitioned to shutdown
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool: shutdown; state=pool::State { lifecycle: Running, num_futures: 1 }
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool:   -> transitioned to shutdown
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: found work while draining; signal_work
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool: signal_work -- spawn; idx=6
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::task: Task::run; state=Running
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::task:     -> not ready
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: Worker::sleep; worker=WorkerId(7)
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker:   sleeping -- push to stack; idx=7
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker:     -> starting to sleep; idx=7
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: Worker::sleep; worker=WorkerId(6)
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker:   sleeping -- push to stack; idx=6
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker:     -> starting to sleep; idx=6
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: found work while draining; signal_work
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool: signal_work -- spawn; idx=6
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::task: Task::run; state=Running
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::notifier: Notifier::notify; id=0x7f315a83f080
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool:     -> submit internal; idx=7
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool: signal_work -- spawn; idx=5
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: stole task
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::task: Task::run; state=Running
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::task:     -> not ready
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::task:     -> task complete
thread 'tokio-runtime-worker-2' panicked at 'assertion failed: !state.is_pushed()', /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.3/src/pool/backup.rs:94:13
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: task complete; state=pool::State { lifecycle: ShutdownNow, num_futures: 0 }
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: shutting down thread; idx=7
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::pool:   -> shutting down workers
stack backtrace:
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: try_steal_task -- signal_work; self=6; from=7
TRACE 2018-06-01T15:54:44Z: tokio_threadpool::worker: shutting down thread; idx=6
   0:     0x557c5609a36e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h97c2ee355456da7d
   1:     0x557c5609fb76 - std::sys_common::backtrace::print::h974dc8ee7853bf72
   2:     0x557c5608f35b - std::panicking::default_hook::{{closure}}::hc44239ea27e554a3
   3:     0x557c5608f033 - std::panicking::default_hook::h9c396404b1734316
   4:     0x557c5608f97e - std::panicking::rust_panic_with_hook::h9fd4111220916022
   5:     0x557c5604ff2f - std::panicking::begin_panic::hfd03be5f3a6a1953
                               at /checkout/src/libstd/panicking.rs:397
   6:     0x557c56035b38 - tokio_threadpool::pool::backup::Backup::start::h22ca4a4e12e7e463
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.3/src/pool/backup.rs:94
   7:     0x557c5602591a - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h432c593a8399cd96
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.3/src/pool/mod.rs:387
   8:     0x557c5602eb2a - std::sys_common::backtrace::__rust_begin_short_backtrace::h2592f448c751fd3e
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
   9:     0x557c56027c8f - std::thread::Builder::spawn::{{closure}}::{{closure}}::hf12d4c6a9e44b59e
                               at /checkout/src/libstd/thread/mod.rs:409
  10:     0x557c5604025a - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha7ab52996ba4c780
                               at /checkout/src/libstd/panic.rs:305
  11:     0x557c560437ef - std::panicking::try::do_call::hc83b8e5abcb71f48
                               at /checkout/src/libstd/panicking.rs:310
  12:     0x557c560a6bf9 - __rust_maybe_catch_panic
  13:     0x557c560436ee - std::panicking::try::hca16b4483a908e53
                               at /checkout/src/libstd/panicking.rs:289
  14:     0x557c56041c0a - std::panic::catch_unwind::ha0ef2aa75ba5be5d
                               at /checkout/src/libstd/panic.rs:374
  15:     0x557c56027a79 - std::thread::Builder::spawn::{{closure}}::hd03c2a72fc204c8d
                               at /checkout/src/libstd/thread/mod.rs:408
  16:     0x557c5602869f - <F as alloc::boxed::FnBox<A>>::call_box::h253ae643a3be39c9
                               at /checkout/src/liballoc/boxed.rs:638
  17:     0x557c5609c12a - std::sys_common::thread::start_thread::hb479404331dbaadc
  18:     0x557c5608fec5 - std::sys::unix::thread::Thread::new::thread_start::h1690a85b1774945a
  19:     0x7f315b96f5a6 - start_thread
  20:     0x7f315b49022e - __GI___clone
  21:                0x0 - <unknown>
^C
```

This appears to be a race condition: it will happen roughly one in five runs.

`tokio` version: 0.1.6
`futures` version: 0.1.21

**Comment by carllerche** [comment]
This sounds like #375

Could you confirm this is fixed on master? I can push a release after that.

**Comment by Twey** [comment]
Confirm, seems to be fixed on master. Thanks!
