### ISSUE TITLE
SemVer breaking change caused by mio upgrade to 0.8

### ISSUE THREAD

**Issue by ecton** [tokio-rs/tokio#4512]
**Version**

`cargo tree | grep tokio`
```
│   │   │   │   └── tokio v1.17.0
│   │   │   │       └── tokio-macros v1.7.0 (proc-macro)
│   │   │   ├── tokio v1.17.0 (*)
│   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   ├── tokio-rustls v0.23.2
│   │   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   │   │   ├── tokio-util v0.6.9
│   │   │   │   │   │   │   └── tokio v1.17.0 (*)
│   │   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   │   ├── tokio-rustls v0.23.2 (*)
│   │   ├── tokio v1.17.0 (*)
│   │   ├── tokio-tungstenite v0.16.1
│   │   │   ├── tokio v1.17.0 (*)
│   │   │   ├── tokio-rustls v0.23.2 (*)
│   │   └── tokio v1.17.0 (*)
│   │   ├── tokio v1.17.0 (*)
│   │   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   ├── tokio-rustls v0.23.2 (*)
│   │   │   ├── tokio v1.17.0 (*)
│   │   ├── tokio v1.17.0 (*)
│   │   ├── tokio-rustls v0.23.2 (*)
│   │   └── tokio-tungstenite v0.16.1 (*)
│   ├── tokio v1.17.0 (*)
│   └── tokio v1.17.0 (*)
└── tokio v1.17.0 (*)
│   ├── tokio v1.17.0 (*)
│   ├── tokio-util v0.6.9 (*)
│   │   ├── tokio v1.17.0 (*)
│   │   ├── tokio-util v0.7.0
│   │   │   └── tokio v1.17.0 (*)
├── tokio v1.17.0 (*)
└── tokio v1.17.0 (*)
└── tokio v1.17.0 (*)
│   ├── tokio v1.17.0 (*)
├── tokio v1.17.0 (*)
│   │   │   ├── tokio v1.17.0 (*)
│   │   │   ├── tokio-util v0.6.9 (*)
│   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   └── tokio-stream v0.1.8
│   │   │   │       └── tokio v1.17.0 (*)
│   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   │   ├── tokio-rustls v0.22.0
│   │   │   │   │   ├── tokio v1.17.0 (*)
│   │   │   ├── tokio v1.17.0 (*)
│   │   ├── tokio-stream v0.1.8 (*)
│   ├── tokio v1.17.0 (*)
│   ├── tokio-stream v0.1.8 (*)
└── tokio v1.17.0 (*)
└── tokio v1.17.0 (*)
└── tokio v1.17.0 (*)
```

**Platform**
Linux, Arch and Ubuntu both show this behavior.

**Description**

BonsaiDb uses fabruic, which uses quinn, which uses quinn-proto, which uses quinn-udp. quinn-udp depends on `mio 0.7.7` and `tokio ^1.0.1`.

After running `cargo update` this morning, my project upgraded to the newest release of tokio, but at runtime I get this panic:

```
thread 'tokio-runtime-worker' panicked at 'mio must be compiled with `os-poll` to run.', /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/shell/udp.rs:9:5
stack backtrace:
thread 'tokio-runtime-worker' panicked at 'mio must be compiled with `os-poll` to run.', /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/shell/udp.rs:9:5
Received Pong from server on websockets
   0: std::panicking::begin_panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:525:12
   1: mio::sys::shell::udp::only_v6
             at /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/shell/udp.rs:9:5
   2: mio::net::udp::UdpSocket::only_v6
             at /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/net/udp.rs:517:9
   3: quinn_udp::imp::init
             at /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/quinn-udp-0.1.0/src/unix.rs:103:84
   4: quinn_udp::imp::UdpSocket::from_std
             at /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/quinn-udp-0.1.0/src/unix.rs:38:9
   5: quinn::endpoint::Endpoint::new
             at /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/quinn-0.8.0/src/endpoint.rs:83:22
   6: quinn::endpoint::Endpoint::server
             at /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/quinn-0.8.0/src/endpoint.rs:71:9
   7: fabruic::quic::endpoint::Endpoint::new
             at /home/ecton/.cargo/registry/src/github.com-1ecc6299db9ec823/fabruic-0.0.1-dev.5/src/quic/endpoint/mod.rs:93:32
```

From BonsaiDb's perspective, this is a SemVer breaking change. The worst part is that this failure happens at runtime, not at compile time.

We will work with quinn to get quinn-udp updated to the new version of Mio, but I felt like this breaking change should be reported.

**Comment by Darksonn** [comment]
Hi. Thanks for reporting this, and I'm sorry about that.

Unfortunately, it seems like the cause of the failure is that quinn requires that the `os-poll` feature of mio is enabled, and also had a dependency on Tokio. Since the set of enabled features is merged across all dependencies, this means that quinn previously got that feature enabled implicitly by depending on Tokio.

Avoiding this kind of breakage is unfortunately pretty much impossible if we ever want to upgrade any of our dependencies in the future.

Quinn can fix this by adding `os-poll` to the list of features they require from mio. They do not need to upgrade mio to fix it.

**Comment by ecton** [comment]
No need to apologize! This report was made due to me not understanding some of the low-level requirements of my dependencies. Not knowing how mio worked, I assumed that what I was experiencing was a SemVer breaking change, not a easy-to-make-feature-combination-issue in quinn-udp.

Thank you for taking the time to check this out and suggest the fix. I'm going to close this issue as I too agree this isn't tokio's problem to solve.

**Comment by Darksonn** [comment]
I mean, strictly speaking, it _is_ a semver breaking change in Tokio. Unfortunately, the Rust language doesn't really provide any way to avoid this kind of breakage.
