### ISSUE TITLE
He reported an error when I ran the test

### ISSUE THREAD

**Issue by Jzow** [tokio-rs/tokio#4722]
```rust
#[cfg(test)]
mod tests {

    use super::*;

    #[tokio::test]
    async fn add() {
        let client = IpfsClient::from_str("http://127.0.0.1:5001").unwrap();
        let data = Cursor::new("Rust");
    
        match client.add(data).await {
            Ok(res) => println!("{}", res.hash),
            Err(e) => eprintln!("error adding file: {}", e)
        }
    }
```

error:

```rust
running 1 test
thread 'api::ipfs_api::tests::add' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /Users/jameszow/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/task/local.rs:308:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test api::ipfs_api::tests::add ... FAILED

failures:

failures:
    api::ipfs_api::tests::add

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.05s
```

When I replace #[actix-web::test] it works normally

**Comment by Darksonn** [comment]
This is because the `actix-web` macro starts a `LocalSet`, and the thing you are testing calls the `spawn_local` method that only works inside a `LocalSet`.
