### ISSUE TITLE
tinyhttp example panics against curl request

### ISSUE THREAD

**Issue by izderadicka** [tokio-rs/tokio#5326]
**Version**

```
$ cargo tree | grep tokio
benches v0.0.0 (/home/ivan/tmp/envoy/tokio/benches)
└── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio)
    └── tokio-macros v1.8.2 (proc-macro) (/home/ivan/tmp/envoy/tokio/tokio-macros)
        └── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
    ├── tokio-stream v0.1.11 (/home/ivan/tmp/envoy/tokio/tokio-stream)
    │   └── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
    │   ├── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
    │   └── tokio-test v0.4.2 (/home/ivan/tmp/envoy/tokio/tokio-test)
    │       ├── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
    │       └── tokio-stream v0.1.11 (/home/ivan/tmp/envoy/tokio/tokio-stream) (*)
    │       └── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
    └── tokio-test v0.4.2 (/home/ivan/tmp/envoy/tokio/tokio-test) (*)
├── tokio-stream v0.1.11 (/home/ivan/tmp/envoy/tokio/tokio-stream) (*)
└── tokio-util v0.7.4 (/home/ivan/tmp/envoy/tokio/tokio-util)
    ├── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
    ├── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
    ├── tokio-stream v0.1.11 (/home/ivan/tmp/envoy/tokio/tokio-stream) (*)
    └── tokio-test v0.4.2 (/home/ivan/tmp/envoy/tokio/tokio-test) (*)
examples v0.0.0 (/home/ivan/tmp/envoy/tokio/examples)
├── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
├── tokio-stream v0.1.11 (/home/ivan/tmp/envoy/tokio/tokio-stream) (*)
├── tokio-util v0.7.4 (/home/ivan/tmp/envoy/tokio/tokio-util) (*)
stress-test v0.1.0 (/home/ivan/tmp/envoy/tokio/stress-test)
└── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
tests-build v0.1.0 (/home/ivan/tmp/envoy/tokio/tests-build)
tests-integration v0.1.0 (/home/ivan/tmp/envoy/tokio/tests-integration)
└── tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
tokio v1.23.0 (/home/ivan/tmp/envoy/tokio/tokio) (*)
tokio-macros v1.8.2 (proc-macro) (/home/ivan/tmp/envoy/tokio/tokio-macros) (*)
tokio-stream v0.1.11 (/home/ivan/tmp/envoy/tokio/tokio-stream) (*)
tokio-test v0.4.2 (/home/ivan/tmp/envoy/tokio/tokio-test) (*)
tokio-util v0.7.4 (/home/ivan/tmp/envoy/tokio/tokio-util) (*)
```

**Platform**

```
$ uname -a
Linux ivan-ThinkPad-T470 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
**Description**
tinyhttp example panics against HTTP requests

running as :

```
$ RUST_BACKTRACE=1 cargo run --example tinyhttp
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/tinyhttp`
Listening on: 127.0.0.1:8080
thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', examples/tinyhttp.rs:172:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: <tinyhttp::Http as tokio_util::codec::decoder::Decoder>::decode::{{closure}}
             at ./examples/tinyhttp.rs:172:29
   4: <tinyhttp::Http as tokio_util::codec::decoder::Decoder>::decode
             at ./examples/tinyhttp.rs:184:17
   5: <tokio_util::codec::framed_impl::FramedImpl<T,U,R> as futures_core::stream::Stream>::poll_next
             at ./tokio-util/src/codec/framed_impl.rs:203:38
   6: <tokio_util::codec::framed::Framed<T,U> as futures_core::stream::Stream>::poll_next
             at ./tokio-util/src/codec/framed.rs:301:9
   7: <&mut S as futures_core::stream::Stream>::poll_next
             at /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/stream.rs:104:9
   8: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at ./tokio-stream/src/stream_ext/next.rs:42:9
   9: tinyhttp::process::{{closure}}
             at ./examples/tinyhttp.rs:49:47
...
```

curl request:

```
$ curl -v localhost:8080/plaintext
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /plaintext HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server

```

**Comment by izderadicka** [comment]
Problem introduced by httparse 1.8, previous version 1.7 works

**Comment by izderadicka** [comment]
Probably related to this https://github.com/seanmonstar/httparse/issues/124
Method str returned by parser is no longer in same buffer as rest of header.
