### ISSUE TITLE
why does AsyncReadExt::read_u8 does not read sequentially?

### ISSUE THREAD

**Issue by holi-java** [tokio-rs/tokio#6039]
**Version**
```none
└── tokio v1.32.0
    └── tokio-macros v2.1.0 (proc-macro)
└── tokio v1.32.0 (*)
```

**Platform**
5.18.4-051804-generic  GNU/Linux

**Description**

`AsyncReadExt::read_u8` does not read bytes sequentially / previous bytes lost.

```rust
use std::pin::Pin;
use std::{
    future::Future,
    io,
    task::{Context, Poll},
};

use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};

pub struct Socks5<T> {
    stream: T,
}

impl<T> Socks5<T> {
    pub fn new(stream: T) -> Self {
        Socks5 { stream }
    }
}

impl<T: AsyncRead + AsyncWrite> Future for Socks5<T> {
    type Output = io::Result<()>;

    fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        let mut stream = unsafe { self.map_unchecked_mut(|it| &mut it.stream) };
        let mut f = Box::pin(async {
            {
                let first = stream.read_u8().await?;
                let second = stream.read_u8().await?;
                //            v---- error: previous 2 bytes was discarded, why?
                assert_eq!(first, 1);
                assert_eq!(second, 2);
                stream.write_all(&[11, 12]).await?;
            }
            {
                let first = stream.read_u8().await?;
                let second = stream.read_u8().await?;
                assert_eq!(first, 5);
                assert_eq!(second, 6);
                stream.write_all(&[13, 14]).await?;
            }
            Ok(())
        });
        f.as_mut().poll(cx)
    }
}

#[cfg(test)]
mod tests {

    use tokio::{
        io::{AsyncReadExt, AsyncWriteExt},
        net::{TcpListener, TcpStream},
    };

    use super::Socks5;

    #[tokio::test]
    async fn run() {
        let port: u16 = 12345;
        let server = TcpListener::bind(format!("127.0.0.1:{port}"))
            .await
            .unwrap();
        let tx = tokio::task::spawn(async move { server.accept().await });
        tokio::spawn(async move {
            Socks5::new(TcpStream::connect(format!("127.0.0.1:{port}")).await?).await
        });

        let mut buf = [0; 100];
        let mut tx = tx.await.unwrap().unwrap().0;
        // Stage 1
        tx.write_all(&[1, 2]).await.unwrap();
        assert_eq!(tx.read_exact(&mut buf[..2]).await.unwrap(), 2);
        assert_eq!(buf[..2], [11, 12]);

        // Stage 2
        tx.write_all(&[5, 6]).await.unwrap();
        assert_eq!(tx.read_exact(&mut buf[..2]).await.unwrap(), 2);
        assert_eq!(buf[..2], [13, 14]);
    }
}
```

Instead, this happened: 
```none
thread 'tokio-runtime-worker' panicked at src/socks.rs:38:13:
assertion `left == right` failed
  left: 4
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'socks::tests::run' panicked at src/socks.rs:191:56:
called `Result::unwrap()` on an `Err` value: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
test socks::tests::run ... FAILED
```

**Comment by Darksonn** [comment]
You're implementing the poll function wrong.

Every time you call `Socks5::poll`, this will create a new future that starts your async block from the beginning, run until it yields for the first time, then destroy the future. If it is polled again, then the async block will start over from the beginning.

You will need to store the boxed future in the struct to keep it alive between calls to poll.

**Comment by holi-java** [comment]
Thanks, is there a way to use await rather than polls everywhere in future?

> You're implementing the poll function wrong.
> 
> Every time you call `Socks5::poll`, this will create a new future that starts your async block from the beginning, run until it yields for the first time, then destroy the future. If it is polled again, then the async block will start over from the beginning.
> 
> You will need to store the boxed future in the struct to keep it alive between calls to poll.

Thanks, is there a way to use await rather than ugly polls everywhere in future?

**Comment by Darksonn** [comment]
My general recommendation would be to not implement `Future` manually at all. Instead, define an async fn and call it directly.

**Comment by holi-java** [comment]
> My general recommendation would be to not implement `Future` manually at all. Instead, define an async fn and call it directly.

I got it, thanks very much!

**Comment by Darksonn** [comment]
You're welcome.

I will close this as it is not a Tokio issue.
