### ISSUE TITLE
Thread Panic : called `Result::unwrap()` on an `Err` value: Os { code: 48, kind: AddrInUse, message: "Address already in use" } in the spawning tutorial tokio

### ISSUE THREAD

**Issue by NightProg** [tokio-rs/tokio#6156]
**Version**
tokio v1.34

**Platform**
Macos 

**Description**
When I try to test the code of the spawning section ([spawning](https://tokio.rs/tokio/tutorial/spawning) the first example) i got this error: 
```
thread 'main' panicked at src/main.rs:7:62:
called `Result::unwrap()` on an `Err` value: Os { code: 48, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

I tried this code:

```rust
use tokio::net::{TcpListener, TcpStream};
use mini_redis::{Connection, Frame};

#[tokio::main]
async fn main() {
    // Bind the listener to the address
    let listener = TcpListener::bind("127.0.0.1:6379").await.unwrap();

    loop {
        // The second item contains the IP and port of the new connection.
        let (socket, _) = listener.accept().await.unwrap();
        process(socket).await;
    }
}

async fn process(socket: TcpStream) {
    // The `Connection` lets us read/write redis **frames** instead of
    // byte streams. The `Connection` type is defined by mini-redis.
    let mut connection = Connection::new(socket);

    if let Some(frame) = connection.read_frame().await.unwrap() {
        println!("GOT: {:?}", frame);

        // Respond with an error
        let response = Frame::Error("unimplemented".to_string());
        connection.write_frame(&response).await.unwrap();
    }
}
```

I expected to see this happen: `GOT: Array([Bulk(b"set"), Bulk(b"hello"), Bulk(b"world")])`

Instead, this happened: 
```
thread 'main' panicked at src/main.rs:7:62:
called `Result::unwrap()` on an `Err` value: Os { code: 48, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

NOTE: the mini-redis-server was running

**Comment by Darksonn** [comment]
That error happens when you try to start a server, but a server is already running.

Close the old server to fix this error. If you can't find it, rebooting your machine should kill it.

**Comment by NightProg** [comment]
I already tried this, but another thing unexpected happens: I didn't get this message: `GOT: Array([Bulk(b"set"), Bulk(b"hello"), Bulk(b"world")])`, it seems like there is while true loop or something like that
