### ISSUE TITLE
`tokio::codec::LengthDelimitedCodec::encode` can exceed buffer size

### ISSUE THREAD

**Issue by Twey** [tokio-rs/tokio#681]
## Version

```
tokio v0.1.11
├── tokio-codec v0.1.1
│   └── tokio-io v0.1.9
├── tokio-current-thread v0.1.3
│   └── tokio-executor v0.1.5
├── tokio-executor v0.1.5 (*)
├── tokio-fs v0.1.3
│   ├── tokio-io v0.1.9 (*)
│   └── tokio-threadpool v0.1.7
│       └── tokio-executor v0.1.5 (*)
│   └── tokio-io v0.1.9 (*)
├── tokio-io v0.1.9 (*)
├── tokio-reactor v0.1.6
│   ├── tokio-executor v0.1.5 (*)
│   └── tokio-io v0.1.9 (*)
├── tokio-tcp v0.1.2
│   ├── tokio-io v0.1.9 (*)
│   └── tokio-reactor v0.1.6 (*)
├── tokio-threadpool v0.1.7 (*)
├── tokio-timer v0.2.7
│   └── tokio-executor v0.1.5 (*)
├── tokio-udp v0.1.2
│   ├── tokio-codec v0.1.1 (*)
│   ├── tokio-io v0.1.9 (*)
│   └── tokio-reactor v0.1.6 (*)
└── tokio-uds v0.2.2
    ├── tokio-io v0.1.9 (*)
    └── tokio-reactor v0.1.6 (*)
```

## Platform

```
Linux uruz 4.14.71 #1-NixOS SMP Wed Sep 19 20:43:49 UTC 2018 x86_64 GNU/Linux
```

## Subcrates

```
tokio
```

## Description

I recently upgraded my version of `tokio_io` and got told that now `length_delimited` lives in `tokio::codec`.  I rewrote my code to use `tokio::codec`, but it appears that the new `LengthDelimitedCodec::encode` can overflow the buffer: I now get the following panic:

```
thread 'tokio-runtime-worker-1' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.10/src/bytes.rs:1530:9
stack backtrace:
   0:     0x55ed95052a3e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h36813192e41b776c
   1:     0x55ed950441a6 - std::sys_common::backtrace::print::h5a58b54515e32953
   2:     0x55ed9504220d - std::panicking::default_hook::{{closure}}::hb9fdc8e4d0483536
   3:     0x55ed95041f80 - std::panicking::default_hook::hbc1f16403be97c99
   4:     0x55ed950428ac - std::panicking::rust_panic_with_hook::hc6ae0e30d7092692
   5:     0x55ed94fd40af - std::panicking::begin_panic::he3681c8de1f5954a
                               at /checkout/src/libstd/panicking.rs:445
   6:     0x55ed94f140bc - <bytes::bytes::BytesMut as bytes::buf::buf_mut::BufMut>::put_slice::h95a4d8b323c077f5
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/<panic macros>:3
   7:     0x55ed94f13919 - bytes::buf::buf_mut::BufMut::put_uint_be::h9948749f2893a4e5
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.10/src/buf/buf_mut.rs:810
   8:     0x55ed94f1c720 - <tokio::codec::length_delimited::LengthDelimitedCodec as tokio_io::codec::encoder::Encoder>::encode::h53b6fcadced8fa34
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/codec/length_delimited.rs:582
   9:     0x55ed94a7d4a0 - <tokio_io::_tokio_codec::framed::Fuse<T, U> as tokio_io::codec::encoder::Encoder>::encode::h02ff1a27a7a325cb
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.9/src/_tokio_codec/framed.rs:225
  10:     0x55ed94abfec6 - <tokio_io::_tokio_codec::framed_write::FramedWrite2<T> as futures::sink::Sink>::start_send::h8411a0d59500708d
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.9/src/_tokio_codec/framed_write.rs:178
  11:     0x55ed94abfa15 - <tokio_io::_tokio_codec::framed_write::FramedWrite<T, E> as futures::sink::Sink>::start_send::h55f6d8bf84400c5c
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.9/src/_tokio_codec/framed_write.rs:87
  12:     0x55ed94a87d78 - <futures::sink::with::With<S, U, F, Fut>>::poll::h5c8e558edc28d858
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/sink/with.rs:108
  13:     0x55ed94a87812 - <futures::sink::with::With<S, U, F, Fut> as futures::sink::Sink>::poll_complete::h65993b21e5ba7104
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/sink/with.rs:143
  14:     0x55ed94a9de04 - <tokio_serde::buffer_one::BufferOne<S> as futures::sink::Sink>::poll_complete::h564fe921d22acafc
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-serde-0.2.0/src/buffer_one.rs:120
  15:     0x55ed94a67c6a - <tokio_serde::FramedWrite<T, U, S> as futures::sink::Sink>::poll_complete::hbc4750189f8ca944
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-serde-0.2.0/src/lib.rs:377
  16:     0x55ed94a8901a - <tokio_serde_bincode::WriteBincode<T, U> as futures::sink::Sink>::poll_complete::h68eccaeb1cf4b1b4
                               at /home/twey/.cargo/git/checkouts/tokio-serde-bincode-31198663bc7371ca/8ac962b/src/lib.rs:183
  17:     0x55ed94a6b17a - <uni_channel::Sender<T> as futures::sink::Sink>::poll_complete::h9feb259d9d255012
                               at /home/twey/path/to/my/source.rs:133
  18:     0x55ed94a9babb - <futures::sink::send::Send<S> as futures::future::Future>::poll::h842bf32e28ffc49e
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/sink/send.rs:54
  19:     0x55ed94a9288d - <futures::future::from_err::FromErr<A, E> as futures::future::Future>::poll::hcf75700ac22c67d9
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/from_err.rs:29
  20:     0x55ed94aa714d - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h1cf0e0be05e92b34
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/map.rs:30
  21:     0x55ed94a8c854 - <futures::future::chain::Chain<A, B, C>>::poll::h585f52ee6544cb84
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/chain.rs:42
  22:     0x55ed94a93519 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::hb8b4c4d1e9aa6ce1
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/and_then.rs:32
  23:     0x55ed94a9270d - <futures::future::from_err::FromErr<A, E> as futures::future::Future>::poll::h96dc444a67b371b7
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/from_err.rs:29
  24:     0x55ed94aa8fed - <futures::future::map::Map<A, F> as futures::future::Future>::poll::hb0d58ac0c94e099b
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/map.rs:30
  25:     0x55ed94a8e391 - <futures::future::chain::Chain<A, B, C>>::poll::h629a543142076558
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/chain.rs:42
  26:     0x55ed94a93459 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h3f9deb499bd763ff
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/and_then.rs:32
  27:     0x55ed94acd3c9 - <futures::future::either::Either<A, B> as futures::future::Future>::poll::h82c2fc1c1753fb3e
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/either.rs:35
  28:     0x55ed94acd2c8 - <futures::future::either::Either<A, B> as futures::future::Future>::poll::h3029f12e7af6cfd6
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/either.rs:36
  29:     0x55ed94acd4e9 - <futures::future::either::Either<A, B> as futures::future::Future>::poll::hc95e680bc69e6060
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/either.rs:35
  30:     0x55ed94a9e0b1 - <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll::h11543dfb7d7ad1d9
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/stream/fold.rs:70
  31:     0x55ed94aa81fd - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h5e621ac08c3e5720
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/map.rs:30
  32:     0x55ed94a8ea7d - <futures::future::chain::Chain<A, B, C>>::poll::h7489bd837c6cc4b0
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/chain.rs:32
  33:     0x55ed94a93579 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::he97931e824f33433
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/and_then.rs:32
  34:     0x55ed94a8bb02 - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::hc1c2823669e1dfd2
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/map_err.rs:30
  35:     0x55ed94aaa0f7 - <futures::future::map::Map<A, F> as futures::future::Future>::poll::hf09ec507b06a6fc8
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/map.rs:30
  36:     0x55ed95020e04 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hb9602c1b1913b448
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/mod.rs:113
  37:     0x55ed94f9ac52 - <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h93673cef3882acb0
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:314
  38:     0x55ed94f9af5f - <futures::task_impl::Spawn<T>>::enter::{{closure}}::h7ee38aeeeab1647b
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:388
  39:     0x55ed94f8fcdd - futures::task_impl::std::set::h003a3132feaa0e93
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/std/mod.rs:78
  40:     0x55ed94f9aeca - <futures::task_impl::Spawn<T>>::enter::hb654964a070114d3
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:388
  41:     0x55ed94f9abd3 - <futures::task_impl::Spawn<T>>::poll_future_notify::h872643010bd750d9
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:314
  42:     0x55ed94fa1b54 - tokio_threadpool::task::Task::run::{{closure}}::h1510df7f78142834
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/task/mod.rs:127
  43:     0x55ed94f89b28 - core::ops::function::FnOnce::call_once::h1d695ce8555cfd88
                               at /checkout/src/libcore/ops/function.rs:223
  44:     0x55ed94f97daa - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha15c1e9375060381
                               at /checkout/src/libstd/panic.rs:308
  45:     0x55ed94f98250 - std::panicking::try::do_call::ha32540d02f95a8fb
                               at /checkout/src/libstd/panicking.rs:310
  46:     0x55ed9505ffa9 - __rust_maybe_catch_panic
  47:     0x55ed94f97fc1 - std::panicking::try::h1da2f77264a1edce
                               at /checkout/src/libstd/panicking.rs:289
  48:     0x55ed94f97f32 - std::panic::catch_unwind::ha2fe493da19db5c2
                               at /checkout/src/libstd/panic.rs:392
  49:     0x55ed94fa1590 - tokio_threadpool::task::Task::run::h9a4f32639890171e
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/task/mod.rs:113
  50:     0x55ed94f7cb4c - tokio_threadpool::worker::Worker::run_task2::haa4b954caffc682a
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:550
  51:     0x55ed94f7c5ab - tokio_threadpool::worker::Worker::run_task::hdb9805bd087f239e
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:451
  52:     0x55ed94f7c1f7 - tokio_threadpool::worker::Worker::try_steal_task::h1ce703726ec38a54
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:418
  53:     0x55ed94f7b7b0 - tokio_threadpool::worker::Worker::try_run_task::h73f93829b416aef5
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:303
  54:     0x55ed94f7b5e5 - tokio_threadpool::worker::Worker::run::hfc8f3ce429a6c59b
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:240
  55:     0x55ed94f123ea - tokio::runtime::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hef7130b8dc3b7bc0
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/builder.rs:238
  56:     0x55ed94f1d06e - tokio_timer::timer::handle::with_default::{{closure}}::h9a8e8356cff081e3
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:94
  57:     0x55ed94f1aa2a - <std::thread::local::LocalKey<T>>::try_with::h0c8ebfa401917230
                               at /checkout/src/libstd/thread/local.rs:294
  58:     0x55ed94f1a704 - <std::thread::local::LocalKey<T>>::with::h4b04e4b10d01a216
                               at /checkout/src/libstd/thread/local.rs:248
  59:     0x55ed94f1cece - tokio_timer::timer::handle::with_default::h3282fe520d2a1259
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:81
  60:     0x55ed94f12420 - tokio::runtime::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h30e163be20694e9b
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/builder.rs:237
  61:     0x55ed94f191a0 - tokio_timer::clock::clock::with_default::{{closure}}::ha9a14b29caa43d96
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:136
  62:     0x55ed94f1aec3 - <std::thread::local::LocalKey<T>>::try_with::h6b4627e9c1d3edb9
                               at /checkout/src/libstd/thread/local.rs:294
  63:     0x55ed94f1a7cd - <std::thread::local::LocalKey<T>>::with::h8794041fb2f60ad6
                               at /checkout/src/libstd/thread/local.rs:248
  64:     0x55ed94f190b6 - tokio_timer::clock::clock::with_default::hb6610e1d7edb0ffc
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:119
  65:     0x55ed94f12465 - tokio::runtime::builder::Builder::build::{{closure}}::{{closure}}::hf4f5f8a2d2935b8c
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/builder.rs:236
  66:     0x55ed94f12b11 - tokio_reactor::with_default::{{closure}}::h7ff49d2ec5b80795
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:229
  67:     0x55ed94f1ac76 - <std::thread::local::LocalKey<T>>::try_with::h0e27700388377fc9
                               at /checkout/src/libstd/thread/local.rs:294
  68:     0x55ed94f1a83d - <std::thread::local::LocalKey<T>>::with::h97cade82d5ded15b
                               at /checkout/src/libstd/thread/local.rs:248
  69:     0x55ed94f128f4 - tokio_reactor::with_default::he254ba0016760bfd
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:212
  70:     0x55ed94f1259f - tokio::runtime::builder::Builder::build::{{closure}}::hcbaa3fda0573f848
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/builder.rs:235
  71:     0x55ed94f99341 - tokio_threadpool::callback::Callback::call::h5fb3fe551cdcb165
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/callback.rs:21
  72:     0x55ed94f7b26e - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::hb1fe4879b17afab4
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:122
  73:     0x55ed94f83ceb - tokio_executor::global::with_default::{{closure}}::h202fe1ff5011eadd
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:192
  74:     0x55ed94f82f33 - <std::thread::local::LocalKey<T>>::try_with::h6e630c9e06ae321e
                               at /checkout/src/libstd/thread/local.rs:294
  75:     0x55ed94f822d4 - <std::thread::local::LocalKey<T>>::with::h52f1c31f2281cc26
                               at /checkout/src/libstd/thread/local.rs:248
  76:     0x55ed94f83bd7 - tokio_executor::global::with_default::h15373ee3356514ff
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:162
  77:     0x55ed94f7b30d - tokio_threadpool::worker::Worker::do_run::{{closure}}::h575287b598121f09
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:120
  78:     0x55ed94f83161 - <std::thread::local::LocalKey<T>>::try_with::h907da8e4a107cf3a
                               at /checkout/src/libstd/thread/local.rs:294
  79:     0x55ed94f8231c - <std::thread::local::LocalKey<T>>::with::h8ad2791223b13adb
                               at /checkout/src/libstd/thread/local.rs:248
  80:     0x55ed94f7b146 - tokio_threadpool::worker::Worker::do_run::h46e0d547728add56
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/worker/mod.rs:111
  81:     0x55ed94fa59b6 - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::hcfe94b53ee8503c7
                               at /home/twey/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/pool/mod.rs:413
  82:     0x55ed94f84bba - std::sys_common::backtrace::__rust_begin_short_backtrace::ha1e05821e0e4edb8
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  83:     0x55ed94fa0217 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h1545ef3f28403706
                               at /checkout/src/libstd/thread/mod.rs:409
  84:     0x55ed94f97d7a - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3aa6c8e9995e34a9
                               at /checkout/src/libstd/panic.rs:308
  85:     0x55ed94f981df - std::panicking::try::do_call::ha271f8a7b23f9462
                               at /checkout/src/libstd/panicking.rs:310
  86:     0x55ed9505ffa9 - __rust_maybe_catch_panic
  87:     0x55ed94f980de - std::panicking::try::ha6c9ae3d9c59f8de
                               at /checkout/src/libstd/panicking.rs:289
  88:     0x55ed94f97eda - std::panic::catch_unwind::h77a7e5b8727dcf45
                               at /checkout/src/libstd/panic.rs:392
  89:     0x55ed94fa0023 - std::thread::Builder::spawn::{{closure}}::h673d429d703eecab
                               at /checkout/src/libstd/thread/mod.rs:408
  90:     0x55ed94fa031f - <F as alloc::boxed::FnBox<A>>::call_box::h811f504a921d8329
                               at /checkout/src/liballoc/boxed.rs:640
  91:     0x55ed950406aa - std::sys_common::thread::start_thread::hf7e3047d4d8b5d44
  92:     0x55ed950433b5 - std::sys::unix::thread::Thread::new::thread_start::h6075c891fcd3c345
  93:     0x7f68a75645a6 - start_thread
  94:     0x7f68a708522e - __GI___clone
  95:                0x0 - <unknown>
```

Unfortunately the code in question is proprietary, so I can't share, but I will attempt to produce a MWE later if the backtrace isn't sufficient.

**Comment by hawkw** [comment]
@Twey thanks for the report! I think #682 should fix the panic you've encountered. Let me know if that's not the case?

**Comment by glebpom** [comment]
Please, release a new tokio version with the bugfix. This is a critical bug.

**Comment by devfans** [comment]
So we have a version with the bugfix included now?

**Comment by tobz** [comment]
This has likely been released for a while, since it was merged back in October.

**Comment by devfans** [comment]
Seems tokio-codec's latest version is still 0.1.1
https://crates.io/crates/tokio-codec
0.1.1 Sep 27, 2018

I am facing the same panic I think and wonder if the fix was already included in the latest release.

**Comment by devfans** [comment]
Seems I was wrong, I found a small bug in my code which is not related to this issue.
